OpenRCT2/Localisation

- data/language/dutch.txt
Met @ThomasDenH's commentaar al verwerkt.
Zoals aangegeven heb ik 'Simplex noise' zo laten staan omdat de meeste Nederlandstalige teksten het ook zo lijken te gebruiken.
> Add Dutch Simplex noise parameters

- data/language/italian.txt
The Italian file will need more updates than just this one, but this one was causing the date display to be completely broken, which I'd say is worse than a few missing strings. It's also a translation that is just within my knowledge of Italian.
> Fix Italian date display

- data/language/dutch.txt
- data/language/english_us.txt
Any text after {VELOCITY} is truncated, so it has to be the last thing in the string.
> 410 km/h lift hill

- data/language/dutch.txt
- data/language/english_us.txt
- data/language/french.txt
- data/language/german.txt
- data/language/hungarian.txt
- data/language/italian.txt
- data/language/polish.txt
- data/language/spanish_sp.txt
- data/language/swedish.txt
Assumes https://github.com/IntelOrca/OpenRCT2/pull/1076 gets merged.
> Add strings for the RCT1 colour scheme and disabling breakdown, mostly fill other languages to make them more useful

- data/language/dutch.txt
Tevens het (ook in RCT1) erg letterlijk vertaalde 'banner' aangepast naar 'lichtkrant': elektronisch scherm met tekst die voorbij gaat.
> NL: awful lot of strings

- data/language/korean.txt
To prevent truncating. It occurs the same stall's name because of their long name.
> Shorten the Fruit Icecream Stall

- data/language/chinese_traditional.txt
- I don't understand what are STR_5612,14,16 referred to, so I just leave them in English until I found out the meaning.
some trivia about the Chinese RCT names:
- 夢幻遊樂園 is the official translation of RCT1, and due to change of the agent, which is also the translator, RCT2 was named as 模擬樂園2.
- 夢幻遊樂園: 資料片 (RCT1: Expansion Pack) is the official (yes, it's quite lazy)Chinese translation for AA. LL was named as Expansion Pack 2002 in a quite subtle and unclear way. To prevent misunderstanding, I use Expansion Pack 2 instead to give users a more straightforward undesrtanding.
> CHT: New strings (Scenario Lists)

- data/language/french.txt
Dates translation is now in the correct French format.
Was: 24ème Sept, an 1
Now: 24 Septembre, année 1
> FR date translation update

- data/language/french.txt
Translated all coasters, corrected "Mini-montagnes junior" into "Montagnes russes junior".
Date corrected + minor corrections
> FR: All coaster translated + date corrections

- .github/ISSUE_TEMPLATE.md
As en-GB is the original file which shouldn't be translated, it's not in the Localisation folder
What we could do is mark it as done like: 
[X] en-GB
> Remove en-GB from template (Suggestion inside)

- data/language/sv-SE.txt
Fixed Swedish translation of STR_0580 saying 1000m (wrong conversion from 300 ft).
> Fixed number in giga-coaster description

- data/language/sv-SE.txt
Oxford comma is not used in Scandinavia.
> Removed usage of oxford comma

- data/language/it-IT.txt
I've made some fixes and I've translated the color names.
**Note to Italian translators**: never translate using the second person ("You saved the game" = "Hai salvato il gioco"), always use the impersonal form ("You saved the game" = "Il gioco è stato salvato"). Also, commands such as "Save Game" are always translated like "Salva **g**ioco" (note the undercase letter). These are common practices in Italian translations.
> it-IT: language fixes, colors translated

- data/language/nl-NL.txt
Zie <https://onzetaal.nl/taaladvies/advies/gradenteken-en-andere-tekens-spatie-of-niet>
> [nl-NL] Add space before temperature degree symbol

- data/language/sv-SE.txt
There were some typos and grammatical errors in some of the Swedish translation strings. As well as some strings where more preferable terminology could be used.
> [sv-SE] Improve some existing translations

- data/language/cs-CZ.txt
User Hurec on the forums posted that money is not being displayed correctly when using the Czech localisation.
For example, a value of €10000 (ten thousand) is displayed as "€10,".
The thousands separator (STR_5151) is empty in cs-CZ.txt.
According to wikipedia, Czech uses a space as the thousands separator.
Updated cs-CZ.txt accordingly. Money displays properly - e.g. "€10 000,00"
> Define thousands separator (STR_5151) in cs-CZ.txt.

- data/language/fr-FR.txt
I was creating my own "Shuttle Loop" coaster until I realized in the coaster's settings that the french translation missed the difference between RCT1 (stop at station) and RCT2 (keep going) powered launch mode.
This PR fixes this problem.
> fr-FR: Make the difference for powered launch coasters

- data/language/zh-TW.txt
Thanks to the smart Github web text editor, odd white space is such a welcoming & re-occurring bug. /s
> zh-TW: fix whitespace issue

- data/language/cs-CZ.txt
- data/language/de-DE.txt
- data/language/it-IT.txt
- data/language/ko-KR.txt
- data/language/nb-NO.txt
- data/language/nl-NL.txt
To correct the "99%" the language checker pushes out on some languages
PS. Wish I could squash them all, but my Github and localisation folder ain't getting along :(
> All languages: Adding missing string 6034

- data/language/en-US.txt
Pretty trivial, I know... but "cattail" is far more common in American English. In fact, I had never
even heard of "bulrushes" before noticing in-game.
Plus the USDA uses "cattail" as well, so I guess it's official
https://plants.usda.gov/core/profile?symbol=TYPHA
> en_US: Use "cattails" instead of "bulrushes"

- data/language/ja-JP.txt
With the new font support on its way, I've picked up where we left off. This adds a bunch of translations and unifies some existing strings a little.
For ride names, I've used the RCT3 fan-translation for reference (e.g. [this page](https://www39.atwiki.jp/rct3jpinfo/pages/81.html).
> ja-JP: add translations for more strings; unify more ride strings.

- data/language/ja-JP.txt
More translations for Japanese. This time, they relate to ride status, food items, finances, and various other things.
> ja-JP: translations for status, food items, finances, misc.

- data/language/ja-JP.txt
More translations! Fixed a missing } for `{STRINGID}` in a few translations, too.
> ja-JP: more guest thoughts, ride/track window strings, misc.

- data/language/ja-JP.txt
Translations for advertisement campaigns, view options, misc.
I've also looked into transcribing the scenario names in katakana. This is a work in progress, and as such not committed yet. It would be useful to have a file with the original English descriptions. These exist for the scenarios from RCT1 in en-GB.txt. Is a similar listing available somewhere for RCT2?
As SV6 limits park names to 32 bytes, some of these transcriptions will have their name chopped off by a few characters. Their names in the scenario selection screen appear just fine. Would this be acceptable, or would you recommend I just transcribe STR_SCNR and leave STR_PARK to the English name in such cases?
> ja-JP: advertisement campaigns, view options, misc.

- data/language/ja-JP.txt
This should make the translation cover most, if not all, of the game's base rides and attractions. The expansion pack's rides will probably be introduced after the rest of the file is done.
NB: from now on, I'll be translating 'landscape' with 地形 (terrain) instead of 景色 (landscape/scenery) to prevent any confusion with 景色物 (scenery).
> ja-JP: object name translations; miscellaneous other translations.

- data/language/ja-JP.txt
This PR addresses the colour list, scenario/park editor, map window, ride/stall/track descriptions, and various miscellaneous strings.
As noted in the relevant commit, most of the ride descriptions were adapted from the Japanese [RCT3 fan translation](https://www39.atwiki.jp/rct3jpinfo/) where ride descriptions matched.
> ja-JP: a bunch more translations

- data/language/ja-JP.txt
This PR finally tackles scenario objectives, as well as some multiplayer terminology and other miscellaneous strings.
Also: スタフ→スタッフ. Apparently, the latter is a more common transcription for 'staff'.
> ja-JP: scenario objectives; some multiplayer terminology; misc

- data/language/ja-JP.txt
This applies #1285. Also commits several changes I hadn't pushed yet:
* Strings for mechanic-related notifications and statuses
* Translations for notification settings
* Change date format order (like #1281)
* Changes transcription for 'player' from プレーヤー to プレイヤー
> ja-JP: apply #1285; various misc changes

- data/language/ja-JP.txt
Adding translations for the ride construction window, and some miscellaneous smaller windows. Also applying #1349.
(I love how 'Seat rotation' can just be translated with 席の回転角, which doesn't need shortening in the interface — cf. 'Seat rot.')
> ja-JP: translations for ride construction; apply #1349

- data/language/pt-BR.txt
Fixed some typos and modified some lines with more correct and concise Portuguese. Also, some strings that should refer to Right-Hand corners (Direita) were mistakenly written as Left-Hand Corners (Esquerda).
> Update pt-BR.txt - Fixed some language mistakes and rephrased some strings

- data/language/pt-BR.txt
It had said "Estilo Reggae" mistakenly.
I don't know if there's a more proper "Portuguese" word for the genre, but [Wikipedia](https://pt.wikipedia.org/wiki/Ragtime) just calls it Ragtime.
> pt-BR: Fixed string 3030, "Ragtime style"

- data/language/en-US.txt
The description for the scenario North America - Grand Canyon uses the UK word neighbouring instead of the US word neighboring.
> Scenario description typo in en-US.txt

- data/language/en-US.txt
There was a space in front of this exclamation point.
> Unnecessary space in en-US.txt

- data/language/es-ES.txt
> es-ES: Updated up to issue #1545

- data/language/cs-CZ.txt
"custom" is a tricky word to translate accurately (hence the parentheses). I substituted the translation with a shorter one, however less descriptive.
> cs-CZ: Apply #1557 (shorter version)

- data/language/nl-NL.txt
- #1630
Multiple translations for "operating mode" are currently in use, "werkmodus" and "bedrijfsmodus". I used "bedrijfsmodus" here since the cheat for unlocking all operating modes currently uses the same translation. Not sure if y'all have a preference for one or the other and if they should all be changed to the same translation.
> nl-NL: Apply #1630

- data/language/nl-NL.txt
The translation of "too many" is incorrectly spelled as "teveel", the correct spelling is "te veel".
Source (in dutch):
https://onzetaal.nl/taaladvies/teveel-te-veel
> Fix typo in nl-NL translations

- data/language/ar-EG.txt
- data/language/ca-ES.txt
- data/language/cs-CZ.txt
- data/language/da-DK.txt
- data/language/de-DE.txt
- data/language/es-ES.txt
- data/language/fi-FI.txt
- data/language/fr-FR.txt
- data/language/hu-HU.txt
- data/language/it-IT.txt
- data/language/ja-JP.txt
- data/language/ko-KR.txt
- data/language/nb-NO.txt
- data/language/nl-NL.txt
- data/language/pl-PL.txt
- data/language/pt-BR.txt
- data/language/ru-RU.txt
- data/language/sv-SE.txt
- data/language/tr-TR.txt
- data/language/zh-CN.txt
- data/language/zh-TW.txt
This PR applies the string removal from https://github.com/OpenRCT2/OpenRCT2/pull/10147 to all other language files.
> Remove unused keyname strings

- data/language/de-DE.txt
This PR applies various assorted grammar and typo fixes for German, all across the file, including:
* Missing hyphenation
* Wrong capitalization
* Wrong punctation
* Other minor grammar-related fixes
> Grammar/typo fixes in German

- data/language/pt-BR.txt
Was the same as 5549 making it appear as if there was a redundant option in the date format dropdown.
> pt-BR: Correct string 5551 (y/m/d should be y/d/m)

- data/language/es-ES.txt
- #1773 
- #1781 
- #1786 
- #1789 
- #1804
- #1809 
- #1821
- #1826
- #1725
- #1675 
Also improving some translations and adding some from original fields.
(This is sourced from #1834 because I think it's great)
> Improve es-ES translation

- data/language/es-ES.txt
Changed "porta papeles" to "portapapeles"
reference: https://dle.rae.es/portapapeles
Also I have fixed some accent marks.
> es-ES: improve translation

- data/language/ja-JP.txt
This adds Japanese translations for the Wacky Worlds and Time Twister scenario titles and park names. The descriptions have been left for a rainy day…
> ja-JP: add translations for WW/TT scenarios

- data/language/fr-FR.txt
- #1847 (a previous PR of mine already translated it but I turned it from singular + plural into singular only)
String `STR_2219` has been updated as well, after looking again at the plural variant of the string, the word `mort` feels "brutal", "violent" for a game like OpenRCT2. So I took the liberty of changing it to `décédé` which is more appropriate when you announce the death of a beloved one.
> fr-FR: Update STR_2219 and fix #1847

- data/language/ko-KR.txt
- #1887 
- #1888 
``{STRINGID}``s should be changed their order in korean so ``{POP16}`` and ``{PUSH16}`` are used in 6376 and 6377
> ko-KR: Apply #1887, #1888

- .github/ISSUE_TEMPLATE/new_and_changed_field_template.md
This is the only template that wasn't recognized, you can see that the header formatting is broken at
https://github.com/OpenRCT2/Localisation/blob/master/.github/ISSUE_TEMPLATE/new_and_changed_field_template.md
But is not at this one:
https://github.com/tupaschoal/Localisation/blob/a4e61b39dfe3d8358abb09510294fe06a3ac3a0e/.github/ISSUE_TEMPLATE/new_and_changed_field_template.md
So I guess this will make it work :D
> Fix new_and_changed issue template

- data/language/pl-PL.txt
I've decided to revert my changes with month naming to a "less bad" version. 
The issue is that there are two word variations depending on usage.
January translates to "Styczeń", but "1st January" translates to "1 Stycznia". 
In the game month names are used to display the current date (bottom right corner) and in a few other places like financial reports. Using "Stycznia" instead of "Styczeń" in this context just seems wrong.  For the current day "1 Styczeń" syntactically incorrect, but it's a common mistake and shouldn't look as bad.
> pl-PL: Fix month names (revert to previous naming)

- data/language/es-ES.txt
> es-ES: Apply #1942

- .github/ISSUE_TEMPLATE/changed_field_template.md
- .github/ISSUE_TEMPLATE/new_and_changed_field_template.md
- .github/ISSUE_TEMPLATE/new_field_template.md
When I tidied up the list, I listed the usernames in the same order as they appear in the readme, which might make things a little easier to maintain/change in the long term (idk)
> Keep user list for notifications sorted by language

- data/language/de-DE.txt
> de-DE: Apply #1979

- .github/workflows/translation_check.yml
The translation check will be now done against the fork master branch and not the upstream master. This should prevent showing changes in case a not fully rebased branch is send to a PR. Resolves #1991
> Check against fork master instead of upstream master

- .github/workflows/translation_check.py
- README.md
Ping @marcinkunert 
This adds some quality of life improvements to `translation_check`, along with some minor refactors:
- Extracts hardcoded path to `en-GB.txt`
- Sorts the language list, so that the output of the check and the comments always list languages alphabetically
- Adds an argparser, so it can be run locally by doing, for example:
`python3 translation_check.py -r data/language/en-GB.txt -m data/language -b data/language`
The default values of the arguments are the hardcoded ones, so that we don't have to use the switches in the workflow. Also note that having this provides an easy way to run the script locally, which makes it a lot faster to validate changes in the script
> Improve translation_check.py usability

- objects/ar-EG.json
- objects/ca-ES.json
- objects/cs-CZ.json
- objects/da-DK.json
- objects/de-DE.json
- objects/en-GB.json
- objects/en-US.json
- objects/eo-OO.json
- objects/es-ES.json
- objects/fi-FI.json
- objects/fr-FR.json
- objects/hu-HU.json
- objects/it-IT.json
- objects/ja-JP.json
- objects/ko-KR.json
- objects/nb-NO.json
- objects/nl-NL.json
- objects/pl-PL.json
- objects/pt-BR.json
- objects/ru-RU.json
- objects/sv-SE.json
- objects/tr-TR.json
- objects/zh-CN.json
- objects/zh-TW.json
This PR introduces object dumps for all supported languages to the Localisation repository. These dumps are intended to become the primary means for translators to translate the strings in OpenRCT2's official JSON objects.
Consider the following snippet from `nl-NL.json`:
```json
"rct2.tt.1920racr": {
"reference-name": "1920s Racing Cars",
"name": "Jarentwintig-raceauto's",
"reference-description": "1920s race car themed go-karts",
"description": "Passagiers racen in go-karts die er uitzien als raceauto's uit de jaren '20.",
"reference-capacity": "Single-seater",
"capacity": "1 persoon per kart"
},
```
The `rct2.tt.1920racr` object contains three strings: `name`, `description` and `capacity`. All three translations are printed in the dump file, as well as their equivalents from the …
> Add JSON object dumps for supported languages

- data/language/eo-OO.txt
- objects/eo-OO.json
- Use the term gokart directly instead of vetkurantaj aŭtetoj (racing minicars)
- Duobla-ferdeka (double-decker) instead of duoble-ferdeka (doubly decked)
- Some objects have inversigitaj (inverted) elements, not renversitaj (overturned) ones
- Pair can be translated more precisely as paro, not duopo (ordered pair)
- Translated some similar object descriptions having to do with riders sitting in pairs of seats,
to give them consistent translations
> eo-OO: Some corrections and object TLs

- objects/eo-OO.json
Fixups:
- Subĉiela instead of fermita
- Duetaĝa instead of duobla-ferdeka
- "Kun kolono da seĝoj" for in-line
- Translate two words starting with M and F that I forgot to translate earlier
- Correct spelling of ĉirkau to ĉirkaŭ
> eo-OO: Translate objs starting with R + fixups

- objects/eo-OO.json
This commit kind of marks the start of the editing and refining process
Let's get the largest tasks out of the way first:
- Standardize format of tree names for most trees
- Use "por ĉaro" instead of "por aŭto" for most ride capacity labels
- Use "parto" instead of "peco" or "ero"
- Verify 100% of objects translated (only 4 purposely same entries, not bad)
> eo-OO: Several fixups for objects

- data/language/eo-OO.txt
- objects/eo-OO.json
Learned at the last minute that `<object> of <material>` should use el rather than de.
Blessed regex + find next functionality
> eo-OO: Use el/da instead of de

- data/language/de-DE.txt
This adds translations for the OpenRCT2 scenery stuff.
> de-DE: Add missing OpenRCT2 scenery strings

- .github/ISSUE_TEMPLATE/changed_field_template.md
- .github/ISSUE_TEMPLATE/new_and_changed_field_template.md
- .github/ISSUE_TEMPLATE/new_field_template.md
- README.md
As I haven't been online or active on GitHub in a long time and doubt I will be in the near feature, I think it's better to remove myself from notifications and as a maintainer for the language sv-SE.
It's better if someone else maintains it, have seen at least one Swedish translator active recently 😃 
**Changes to README.md:** Moved down the language to "Not maintained", made the label yellow and replaced the text with 'outdated', _not sure if it's better to leave it yellow and call it 'Maintained'._ _(also not sure why it removed spaces at the end of other rows)_
Want to thank everyone and I hope this project keeps on expanding and flourishing 😄
> Remove myself from notifications + maintainer

- objects/ko-KR.json
Fix that there is no ``공원``(park) in the original string.
> ko-KR: Fix a translation

- .gitignore
Adds two commonly generated files to the `.gitignore`
- `.DS_Store` which macOS generates several of in various folders to store folder attributes
- `result.md` which is produced by the `translation_check.py` script when run locally as described in the project readme
> Add .DS_Store and result.md to .gitignore

- data/language/ko-KR.txt
- #2199
Currently Korean both uses the same word, ``팻말`` as translations of ``banner`` and ``sign``.
> ko-KR: Apply #2199

- data/language/ko-KR.txt
It was my mistake, I thought ``Dragon's Cave``, not cove 😂
> ko-KR: Fix mis-translation for Dragon's Cove

- data/language/fi-FI.txt
Miscellaneous consistency improvements and wording tweaks for `fi-FI`.
- Reword to get around OpenRCT2/OpenRCT2#15452 (would still prefer the fix outlined in that issue to happen for more natural sounding wording)
- Reword to very clumsily get around OpenRCT2/OpenRCT2#1514
- Consistent spelling of `pizza`
- Consistent translation of `sub sandwich`, `path`, and mouse controls
- Change translation of `load`
- Improve translation of scenario goal descriptions, advertising campaign notifications, and thoughts around expensive shop items
- Avoid ambiguity in translation for "Tidiest park award" that could mean "Coolest park award"
> fi-FI: Consistency and tweaks

- data/language/fr-FR.txt
French "Direction" couldn't be used as the "D" initial is already used in the inspector window. "Orientation" in this context is synonymous.
- #2243
> fr-FR: Apply #2243

- data/language/nl-NL.txt
> nl-NL: Apply #2243

- data/language/fr-FR.txt
There's no good translation for "legacy" in French. I chose "classique" to denote the old way of doing it.
- #2251
> fr-FR: Apply #2251

- data/language/sv-SE.txt
- #2144 
- #2149 
- #2158 
- #2165 
- #2176 
- #2199 
- #2205 
- #2214 
- #2220 
Hello :)
Started playing the game again and realized some stuff in-game wasn’t translated.
I've added some of the open issues where SV-SE have not yet applied.
**Regarding some strings:**
STR_1849 - Removed the last part because it isn't in use anymore _(the theme of the songs used to be in brackets)_
STR_2991 - Banner and sign mixed up
_STR_6435 - Maybe better to translate as "Stoppade vandaler"?_
> sv-SE: Apply #2144, #2149, #2158, #2165, #2176, #2199, #2205, #2214, #2220

- data/language/sv-SE.txt
This was translated to the exact same as the Hypercoaster (STR_6105) for some reason. I've changed it to its original name from the Swedish version of RCT2
> sv-SE: corrected name of twister roller coaster

- data/language/fr-FR.txt
> fr-FR: Apply #2284 & #2286

- data/language/fr-FR.txt
- #2294
---
I left the verb out of the shortcuts strings in order to be consistent with the other transparency shortcuts.
> fr-FR: Apply #2294

- data/language/eo-ZZ.txt
My assumption for string 6493 was that it was shown before loading and thus "some data may be lost" was future tense, but I was recently informed that it actually shows _after_ loading, so I've fixed the tense for one of the words to be more accurate.
> eo-ZZ: Minor fix for string 6493

- objects/de-DE.json
This PR changes the German object translation, mostly with regards to passenger capacities. It uses consistent wording, and fixes some minor translation mistakes.
It also changes the German word "Wagon" / "Waggon" consistently to "Waggon".
> German: Consistent capacity translations

- .github/ISSUE_TEMPLATE/changed_field_template.md
- .github/ISSUE_TEMPLATE/new_and_changed_field_template.md
- .github/ISSUE_TEMPLATE/new_field_template.md
- README.md
This applies the suggestion I gave in #2315. I've made separate commits for >1y inactivity and >6mo inactivity, but personally I think we should go for 6mo tracking, as it seems enough time.
Once (if) this is merged, I can go after all issues to check those languages out and close if all active are fulfilled.
> Close #2315: Stop tracking language and maintainers >6mo inactive

- data/language/it-IT.txt
Fixed typo on STR_1382, Unified terminology for Left and Right when in brackets or abbreviated with "Sx" and "Dx" (before was mixed), Added strings from 6499 to 6514.
- #2369 
- #2378 
- #2387
- #2388
- #2386
- #2414
> it-IT: Apply #2369, #2378, #2386, #2387, #2388, #2414 + fixed typo at STR_1382 + Sx and Dx abbreviation

- objects/en-US.json
I noticed that a few objects still had grey in their name in en-US, this fixes that.
> Objects en-US Grey > Gray

- data/language/ca-ES.txt
- Better use of preposition "per": changed in some places with "per a", "per tal que" and other variations.
- Change "escollir" with "triar" in some cases.
- Add a space between number and % symbol (Catalan rules about this are not the same as in English; I am not using a non-breaking space as I don't know whether OpenRCT2 will handle it right).
- Replace more uses of gerunds instead of the more appropriate present tense.
- Other small amends.
> ca-ES: Amend some strings

- data/language/es-ES.txt
Today I was playing OpenRCT2 and I've noticed that the string 6537 is to long to fit the cheats window, so I've edited the string.
Before:
After:
> es-ES: Make string 6537 shorter

- data/language/pl-PL.txt
Fixing some translation errors in Polish localization, like names of the options too long to fit in the window they supposed to fit in or incorrect spelling in autosave interval option.
> Fixing some translation errors in Polish localization

- data/language/es-ES.txt
Edited `STR_1898`, `STR_1905` and `STR_1906` to fit in the Financial Summary window, and `STR_1897`, `STR_1899`, `STR_1907` for a better clarification, I've used the original game translation as reference.
Before/After:
----
Also edited `STR_6361` to fit in the Options window, and `STR_6362` to add a missing pronoun.
Before:
After:
> es-ES: Modify some strings to fit in the Financial Summary window and STR_6361 to fit in the Options window

- data/language/de-DE.txt
- objects/de-DE.json
This PR fixes some typos and mistakes of the German translation. Also includes string parameters that were overlooked for some reason.
> Fix some German typos

- data/language/pt-BR.txt
Fixes typo on STR_1487. 
`sento` is `I sit`, and `sinto` is `I feel`.
> pt-BR: Fix typo on STR_1487

- data/language/es-ES.txt
- #2678
- #2679 
- Related: made translations of the word "wall"/"fence" consistent across contexts
- Fix: "Remover" (false friend) for natural "Eliminar"
> es-ES: Apply #2678, #2679 + improve "wall" wording consistency

- data/language/es-ES.txt
> _none_
- Fix mistralations of the verb"remove"
> es-ES: fix "remover" mistranslations

- data/language/de-DE.txt
- changed "rauh" to "rau", which is the correct spelling since 1996
- removed the full stop at the end of some sentences, where there is no full stop in similar sentences
> de-DE: fix a typo and improve formatting consistency

- data/language/de-DE.txt
STR_6497 is:
Click on a tile to show its tile elements.{NEWLINE}Ctrl + click a tile element to select it directly.
The previous german translation said:
Click on a tile to show its tile elements.{NEWLINE}Ctrl + click a tile to select it directly.
> de-DE: Fix translation of STR_6497

- data/language/de-DE.txt
Same typo as in 95d0c00cee4285e44d01c8a336e41294a67e8dea
> de-DE: Fix typo

- data/language/de-DE.txt
The sentence should not contain in upper case after the hyphen. Either it must continue in lower case or the hyphen can be changed to a full stop.
- Argument for the former is that it is closer to the english sentence.
- Argument for the latter is that it is more consistent with STR_6516 and STR_6517.
- A (subjective) choice was made for the latter.
> de-DE: adjust translation of STR_6515

- data/language/sv-SE.txt
"track design" occurs 39 times. In the swedish translation, it is translated to
- "bandesign" 32 times
- "spårdesign" 5 times
- "åktursdesign" 2 times
This commit changes "spårdesign" and "åktursdesign" to "bandesign".
"track designs manager" occurs 4 times. In the swedish translation, (after the change above) it is translated to
- "bandesignhanterare" 3 times
- "bandesignredigeraren" 1 time
This commit changes "bandesignredigeraren" to "bandesignhanterare".
Furthermore, it removes a hyphen in "Bandesign-hanterare" in STR_3336.
> sv-SE: improve consistency of track design translation

- data/language/de-DE.txt
It does not make sense to abbreviate only two letters. Space-wise, the english version is much longer.
> de-DE: remove abbreviation in 1673

- data/language/de-DE.txt
Although the english word 'shift' is sometimes used in german, the translation uses the german word 'Umschalt' in other places  (e.g. 2782, 6413-6415).
> de-DE: adjust translation of 'shift'

- data/language/de-DE.txt
Honey dew is a melon fruit or a sugar-rich sticky substance secreted by various animals. The colour refers to the former, the previous translation to the latter.
> de-DE: changed colour translation of honey dew

- data/language/sv-SE.txt
- #2327
- #2328
- #2345
- #2354
- #2369
- #2378
- #2386
- #2387
- #2388
- #2414
- #2430
- #2446
- #2472
- #2473
- #2501
- #2509
- #2520
- #2527
- #2535
- #2550
- #2551
- #2562
- #2563
- #2572
- #2578
- #2594
- #2602
- #2609
- #2620
- #2625
- #2631
- #2641
- #2650
- #2658
- #2659
- #2678 
- #2679 
- #2692 
I also added some fields of #2509, #2527 and #2562, but did not handle all changed or added fields of these issues yet.
Lastly, I added some detail to STR 0582.
> sv-SE: add new fields to swedish translation 6494-6596

- data/language/nb-NO.txt
Noticed several strings were left empty, so filled them in. 
Removed # descriptive lines and empty spaces that weren't present in the current en-GB. 
Translated some words that were missed.
Fixed some awkward wording and typos.
> nb-NO: Filled in missing strings + small fixes

- objects/en-US.json
This seems like a slight oversight which was inherited from vanilla, as the "American Football Helmet" is just "Football Helmet" in en-us while the actual american football scenery pieces themselves were still just known as "American Football" as they were in en-gb. This fixes that so they're both known as just "Football" in en-us.
> Objects en-us American Football > Football

- data/language/en-US.txt
Changes dodgems to bumpers in en-us for consistency with the dodgems vehicle objects which are called bumper cars in en-us.
> en-US Dodgems > Bumper Cars

- objects/en-US.json
The Bobsleigh Coaster ride type is known as the "Bobsled Coaster" in en-us, but this change was not reflected on the vehicles for the ride type. This fixes that.
> en-us Bobsled consistency

- data/language/en-US.txt
This name has puzzled me for years, i've never once seen this ride type refered to as a "Tunnel of Horror" in real life and almost always see it refered to as a Ghost Train, Haunted Mansion Ride, or just simply Dark Ride. I've opted for removing it so that it falls back to "Ghost Train" from en-GB but i am open for the other two options i mentioned if those might make more sense in en-US vs Ghost Train.
> en-US: Remove "Tunnel of Horror" for falling back to "Ghost Train"

- data/language/en-US.txt
- objects/en-US.json
The 3D Theater localization is a misnomer as Cinema and Theater are distinct terms, with Cinema refering to films specifically and it doesn't seem to be an Americanism so the original en-GB is still correct.
For the ATM i've decided to go with "ATM" instead of "A.T.M." as periods don't seem to be frequently used for abbreviating it at least in regards to en-US specifically from what i could tell. I've also changed this for the string used in the map window.
> en-US: Remove "3D Theater" and apply ATM localization to object.

- data/language/fr-FR.txt
- #2794
- #2801 
- #2806 
- #2814 
- #2815 
- #2821 
- #2826 
Also fix an old string being too long and going out of the settings window.
> Apply #2794, #2801, #2806, #2814, #2815, #2821, #2826

- data/language/es-ES.txt
- #2814
- #2815
- Consistent translation of "path": it was references as "camino" or "sendero"
- "sendero" is more faithful to footpath whereas "camino" would be any kind of trail
- "sendero" usage was more frequent than "camino" already in the translation
> es-ES: Apply #2814, #2815 + consistent path translation

- data/language/tr-TR.txt
Dear maintainers,
First of all thanks for maintaining this game. While I was playing, I have seen that Turkish translations had a lot of typos (and probably still there will be after this PR). But still I wanted to improve the translations and I have changed a couple of strings.
I tested in my game and some strings were English, even though I translated to Turkish, I don't know if OpenRCT2 supports unicode completely (I assume it is) but still if an experienced maintainer can take a look why, it would be a huge help.
Long story short, I am proposing an improvement for tr-TR since it is unmaintained for a while (yet still I cannot be a maintainer since I do not have enough time). Feel free to give feedback. Hope this helps.
Best,
Ozan
> tr-TR: Fixed typos and added translations for the untranslated lines

- data/language/de-DE.txt
'Eingang' means 'entrance' but not 'entry' in the sense of an index entry.
> Fix STR_6603 in de-DE

- data/language/sv-SE.txt
STR_5612: "Spök" literally means ghost, but it is not a word that is commonly used in the context of ghost elements in computer games. "Skiss" means sketch, draft or outline, which rather translates the idea of what it is.
STR_5961: "entré" means entry in the sense of entrance, but not in the sense of a list item.
> Improve STR_5612 and STR_5961 in sv-SE

- .github/workflows/translation_check.yml
Moving to a supported version of the action
> Update CI to checkout@v4

- data/language/pl-PL.txt
- objects/pl-PL.json
- Added a missing object description
- Improved existing translations 
- Shortened cheat descriptions, they should now fit in the window 
- Fixed some typos
> pl-PL: improve translations, shorten cheats, fix typos

- objects/ar-EG.json
- objects/ca-ES.json
- objects/cs-CZ.json
- objects/da-DK.json
- objects/de-DE.json
- objects/en-GB.json
- objects/en-US.json
- objects/eo-ZZ.json
- objects/es-ES.json
- objects/fi-FI.json
- objects/fr-FR.json
- objects/hu-HU.json
- objects/it-IT.json
- objects/ja-JP.json
- objects/ko-KR.json
- objects/nb-NO.json
- objects/nl-NL.json
- objects/pl-PL.json
- objects/pt-BR.json
- objects/ru-RU.json
- objects/sv-SE.json
- objects/tr-TR.json
- objects/uk-UA.json
- objects/zh-CN.json
- objects/zh-TW.json
With the scenario text PR in, this PR updates the object string dumps for all languages, sorted by object id.
This PR as a whole has a pretty terrible diff, as the previous dump was apparently not ordered by id. The first commit orders the files in-tree by object identifier key, while the second commit brings the dumps up-to-date.
> Update object string dumps

- data/language/pl-PL.txt
- objects/pl-PL.json
Found some more things to fix. I think the objects file can be left alone for now, at least until the new Wooden Twister is added.
pl-PL.json:
- almost all rollercoasters that had just the word "kolejka" in their name, started with that word, except for three, so I adjusted them for consistency,
- changed the RCT1 Corkscrew name and description to be the same as RCT2,
- capitalized pronouns,
- better name for Dynamite Dunes,
- smaller fixes.
pl-PL.txt:
- mostly small fixes and improved consistency.
> pl-PL: Fix and improve

- objects/ru-RU.json
Here's the second part of the Russian localisation update.
You may have noticed the enormous size of this patch... unlike the UI strings, which just needed some minor fixes and updates, this one is a complete rewrite of all the text. This is out of necessity: this file is the *most baffling* array of strings I have seen in my entire life. The problems with the current one can be summarized as follows:
- The scenery elements have had all descriptors stripped from them, reduced to base nouns, and reused as much as possible. You want a "Heavenly Bath Roof"? Sorry mate, all I can give you is a "Pool Part". An Atlas Statue? No, you get a "globe"! Many have been reduced to simply "block" or "part" with no other clarification.
- The ride descriptions, likewise, were stripped of all flavor text, …
> ru-RU: Retranslate objects JSON

- data/language/pl-PL.txt
- #3005
- #3009
I've also unified the translations of "security guard" to "strażnik" and fixed STR_6675 and STR_6676, where "guest" was used instead of "peep".
> pl-PL: Apply #3005, #3009

- data/language/es-ES.txt
- #2945
Apart from that, I addressed some small issues I came across:
- "cuadrícula": added missing accents
- "Mín/máx": coherency across strings + all accented
- "Clic" usage over "click": IMO "click" is better but ES dictionary has yet to accept it+ there were more strings using "clic"
- Track design / designer: coherency across strings + upper/lower case more similar to EN
- "Paisaje": upper/lower case more similar to EN
- Translated STR_2685 (simplex parameters)
Btw sorry for the absence, it's being some busy months!
Best regards :frog:
> es-ES: Apply #2945 + tweaks

- data/language/pl-PL.txt
- #3035
- #3037
I changed "clockwise" and "anti-clockwise" to "right" and "left" to make it fit in the menu, and kept the original wording in the tooltip.
> pl-PL: Apply #3035, #3037

- data/language/en-US.txt
I added localizations for US English to the text and tooltip of the "Randomise all" button in the vehicle color portion of ride windows. 
I also localized something about color schemes that I can't find in-game or in [UiStringIds.h](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/UiStringIds.h) on the core repo. I'm not sure if they're unused, because an override for the nearby [STR_6501](https://github.com/OpenRCT2/OpenRCT2/blob/113928a2512bda915b2d2fd1906403894d61b4cb/data/language/en-GB.txt#L3556) exist in the en-US file. I localized the other strings anyways just to be safe.
> en-US: Localized text for color schemes and randomizing vehicle colors

- data/language/cs-CZ.txt
Please review with care.
STR_3140 is no more present in en-GB, which renders it redundant in cs-CZ
> cs-CZ: Remove STR_3140

- objects/cs-CZ.json
- #1625
__________
Translator's note: word "Pagoda" is the same in en-GB and cs-CZ, as it is a loan word coming from sanskrit (via portuguese)
> cs-CZ: Apply #1625

- objects/cs-CZ.json
Fix confusing and misleading translations, filled in missing parts of strings.
Note:
1. parts of strings "(sloped)" "(stairs)" etc. can not be omitted in translations, as once both RCT1 and 2 assets are loaded into single scenario, Footpaths window becomes a confusion of the highest order.
2. Translations containing "crazy paving" had to be changed, as the czech phrase "šílená cesta" can be perceived as having very negative connotations. Translations containing "dirt" had to be changed, since they mistranslated the word as _muddy_
> cs-CZ: Fix existing translations of objects in *.footpath_surface.*

- data/language/cs-CZ.txt
- fix capitalization
- fix typos
- unified translation to use same phrases all through the game (STR_2390, -93, -94 & STR_2402, -06)
- shortened text in order not to overlap in UI (STR_6128, 6745)
> cs-CZ: Improve strings related to scenario play and creation

- data/language/es-ES.txt
Hello! long time :)
- #3005
- #3009
- #3014
- #3019
- #3024
- #3035
- #3037
- #3045
Btw, will probably create a PR to change all "rizo" related words for equivalent "loop"
* I kept it at the beginning for consistency
* But it sounds quite weird, IMO you can see some English words like this in themeparks so it fits
* Other langs keep "loop" similarly e.g. es-CA or pt-BR
Why? (added on edit)
* "rizo" *could* be used for a twisting shape something, but is more commonly used for hair "curls"
* My guess is that "rizo" was picked to try to differentiate "ciclo" "vuelta" "giro", which all could mean "loop"...
* In fact, "vuelta" would be the most natural, but could be too easly confused with "ciclo" or even "ride"
* It will always be a compromise!
* In Spanish nowdays you …
> es-ES: Apply #3005, #3009, #3014, #3019, #3024, #3035, #3037, #3045

- data/language/sv-SE.txt
Added missing translations 6656-6791 (inclusive)
- #3211 
- #3147 
- #3130 
- #3124 
- #3120 
- #3112 
- #3094 
- #3082 
- #3076
- #3069 
- #3060 
- #3056 
- #3024 
- #3019
- #3014
- #3005 
- #2999 
- #2981 
- #2941 
- #2938 
- #2936 
- #2928 
- #2917
- #2909 
- #2897 
- #2895 
- #2894
Note, I'm unsure about STR_6675 (Peep Names) and STR_6676 (At least one peep names object must be selected). https://github.com/OpenRCT2/OpenRCT2/pull/22758
The Norwegian translation is using "Bezoekersnamen" meaning "Visitor names" while the Danish translation is using "Peep-Namen" meaning "the Peep Name".
Options I have considered are:
- Peep-namn (Peep name)
- Peep-namnen (The Peep names)
- Gästnamn (guest name)
- Gästnamnen (the guest names)
The choice here is "Peep-namn" as it is …
> sv-SE Added missing translations 6656-6791

- data/language/sv-SE.txt
- #3009
STR_6724 added in #3233
note.
"parkentré" is an unspecified singular form.
While the plural is "parkentréer", it is not what I picked because it is generally used for the area where an entrance is placed.
"Parkingångar" is plural form of "Parkingång". This word specified the entrance itself and not the surrounding area.
> Update sv-SE for #3009

- data/language/sv-SE.txt
"_Gokart_" is the singular form.
To match "_Go-Karts_", I changed it to "_Gokarter_"
See [here](https://sv.wiktionary.org/wiki/gokart) for why "_Gokarter_" is used over "_Gokart_" and "_Gokarts_".
> Update sv-SE with corrected grammar for STR-0024

- objects/cs-CZ.json
Notes: Given names of scenarios and parks are not translated by intention, explanation was partialy already given in https://github.com/OpenRCT2/Localisation/commit/3737477407b195e1c0e7f64b82a60a6c38a703fe and in second order: most avalible informations about OpenRCT2 is presented in English, and general audience trying to translate once translated given names back would lead to even greater confusion, maybe even to "confusion of the highest orda"
> cs-CZ: Add translation for RCT1 scenario meta objects

- data/language/cs-CZ.txt
- objects/cs-CZ.json
Improve legacy transport rides translations, change confusing translations, change translations where car of given ride is mistaken for ride itself.
For ease of review, screenshots included, gray being the current state, colored being the PR
_____________
**Change translation for two different transport rides being translated into same name - it looked like a interface bug:**
____________
**Chairlift listed its cars as "chairlift ride":**
____________
Minor changes not shown in screenshots
> cs-CZ: Improve transport rides translations

- data/language/cs-CZ.txt
- objects/cs-CZ.json
Follow-up to:
- #3275 
- #3276
Improve legacy transport rides translations, change translations that were out of line, change translations where car of given ride is mistaken for ride itself. 
_________________
Sample of changes being submitted - gray being the current state, colored being the PR
Note: "raft" translates to Czech as "vor", whereas "raft" in czech is used only for (semi)inflatable whitewater vessels, thus forming example of "false friends".
_______________
______________
(Not only) improve translation of "water jets", which were were mistaken for 'water skis' in legacy translations; change translations where car of given ride is translated completely out-of-line.
> cs-CZ: Improve transport water rides translation

- objects/cs-CZ.json
Follow-up to:
- #3275
- #3276
- #3286
Improve legacy translation, improve a few names to be more appealing, improve confusing and out of line descriptions. In some cases, change capacity descriptions to fit overall translation style. Add missing translation for `rct1.ride.go_karts`
_____________
Sample of changes being submitted - gray being the current state, colored being the PR
____________
Notably _Béčková pavoučí jízda_ implied that ride itself is of inferior quality, which gets improved by changing to _Twist s béčkovým pavoukem_, which, well - sounds as you gonna twist with B-grade spider - and thus is much more appealing.
____________
Change capacity translation to fit overall translation style. Omit word _jízda_ as unfitting translation of "ride". Slight touch-up to style of …
> cs-CZ: Improve thrill rides translation

- objects/cs-CZ.json
Follow-up to:
- #3275
- #3276
- #3286
- #3288
Fix "My hovercraft is full of eels" grade confusing and mismatched translations. Improve legacy translation, improve a few names to be more appealing and more understandable. Fix translations where car of given ride is wrongly translated as ride itself. Add a few missing translations.
__________
Showing overview of changes, left gray current, right colored PR (a lot of description edits not shown)
PR continues with part 2, half of the strings shown in screenshots are there, as it was split for ease of review.
> cs-CZ: Improve roller coaster translations (1 of 2)

- data/language/cs-CZ.txt
- objects/cs-CZ.json
Follow-up to:
- #3275
- #3276
- #3286
- #3288
- #3293
Fix "My hovercraft is full of eels" grade confusing and mismatched translations. Improve legacy translation, improve a few names to be more appealing and more understandable. Fix translations where car of given ride is wrongly translated as ride itself. Add a few missing translations.
> cs-CZ: Improve roller coaster translations (2 of 2)

- objects/cs-CZ.json
Fix a few RCT1 ride objects translation somehow omitted by improvements #3293 & #3294, improve translation of `rct2tt.ride.softoyst`. Unify words used in `"capacity"` descriptors to make translation look not glued, yet well polished.
> cs-CZ: Minor fixes in objects

- .github/workflows/translation_check.py
This prints the summary for each language only once, which makes it easier for maintainers to check what they need to do and should greatly reduce the size of the CI job log
> Simplify translation_check.py to dump once per language

- .github/workflows/translation_check.yml
**Limit running Translation Check only to PR-s that touch text files in data/language**
Due to reason that it is unnecessary to re-run it when  e.g. GitHub workflows are being modified, or when objects JSONs are being modified, since it does not perform any operations with aforementioned.
_____________
**This change bring benefits:**
🌿 removes unnecessary actions performed by computers, which consume electricity, therefore it is ecological
😌 committers and maintainers will receive less unwanted messages, and thus will be calmer
#️less reports passing thru discord #github
_____________
**I had tested this** (made a [mock-up copy of this repository](https://github.com/tygrysek90/l10n-action-ideas-testing/pulls) and testing modifications on that (since on fork one needs to be in master, …
> Scripting: Limit triggering Translation Check

- data/language/cs-CZ.txt
- #3346
______________
_Translator's note:_ since this string is a label to advanced (and debug) function, an approach same as for `STR_5902` was chosen, as well as this style is in line with https://github.com/OpenRCT2/Localisation/pull/3344 - for advanced functions, where translation can be confusing (since there are almost none available reading/videos about OpenRCT2 in the Czech language, let alone about 'expert' debug functions) the English text is displayed alongside, facilitating easy understanding by users speaking both Czech and English, while still bringing suitable translation to those who do not speak English.
> cs-CZ: Apply #3346
