OpenRCT2/Localisation

data/language/fr-FR.txt
=> fr-FR: Apply #1858 #1862 #1866

data/language/hu-HU.txt
- #1850
- #1858
- #1862
- #1866
=> hu-HU: Update + Apply #1850 #1858 #1862 #1866

data/language/pt-BR.txt
=> pt-BR: Apply #1876

data/language/en-US.txt
=> en-US: Apply #1773

data/language/de-DE.txt
=> de-DE: Apply #1876

data/language/it-IT.txt
=> it-IT apply #1876 and other fixes

data/language/fr-FR.txt
- #1876 
I also corrected some typos, fixed texts overflowing windows, and rewrote some strings to make the translation consistent.
=> fr-FR: Apply #1876, fix typos and improve overall consistency

data/language/fr-FR.txt
=> fr-FR: Apply #1887 #1888

data/language/pt-BR.txt
=> Apply #1887 #1888

data/language/de-DE.txt
=> de-DE: Apply #1887, #1888

data/language/hu-HU.txt
=> hu-HU: Update + Apply #1876 #1887 #1888

data/language/it-IT.txt
=> it-IT apply #1887, #1888, #1898

data/language/de-DE.txt
=> de-DE: Apply #1903, #1898

data/language/ko-KR.txt
=> ko-KR: Apply #1903

data/language/cs-CZ.txt
=> cs-cz apply #1903

data/language/pt-BR.txt
=> pt-BR: Apply #1903

data/language/fr-FR.txt
=> fr-FR: Apply #1898 #1903

data/language/pl-PL.txt
- #1821
- #1826 
- #1847 
- #1844
- #1850
- #1862
- #1866
- #1876
- #1887
- #1888
- #1903
=> pl-PL: Updated polish translations

data/language/pl-PL.txt
I've added couple ride names and improved a few translation issues
=> Polish translation improvements

data/language/pl-PL.txt
=> pl-PL: Apply #1916, #1917

data/language/pt-BR.txt
=> pt-BR: #1916-17

data/language/ko-KR.txt
=> ko-KR: Apply #1916, #1917

data/language/fr-FR.txt
=> fr-FR: Apply #1916 #1917

data/language/cs-CZ.txt
=> cs-cz apply #1916 #1917

data/language/ko-KR.txt
This PR fixes a number of minor Korean strings
=> fix minor korean strings

data/language/de-DE.txt
[I've also submitted a PR in the objects repository](https://github.com/OpenRCT2/objects/pull/123) to replace all "Skooter" by "scooter" in the German localization.
=> Fix spelling mistakes in German localization

data/language/it-IT.txt
=> it-IT new strings

data/language/ca-ES.txt
- #1917
- #1916
- #1903
- #1801
- #1888
- #1887
- #1876
- #1866
- #1858
- #1862
- #1850
- #1847
- #1844
- #1826
- #1821
- #1813
- #1809
- #1804
- #1795
- #1789
- #1786
- #1781
- #1773
- #1737
- #1745
- #1755
=> ca-ES: Apply #1917 #1916 #1903 #1898 #1888 #1887 #1876 #1866 #1858

data/language/de-DE.txt
=> de-DE: Apply #1916, #1917

data/language/hu-HU.txt
- #1898
- #1903
- #1916
- #1917
- #1929
=> hu-HU: Apply #1898 #1903 #1916 #1917 #1929

data/language/cs-CZ.txt
=> cs-cz apply  #1929

data/language/pt-BR.txt
=> pt-BR: Apply #1929

data/language/de-DE.txt
=> de-DE: Apply #1929

data/language/it-IT.txt
=> it-IT apply #1929

data/language/fr-FR.txt
=> fr-FR: Apply #1929

data/language/it-IT.txt
Some fixes in the Italian translation.
I've reduced the length of STR_6153 because it didn't fit the space.
=> it-IT translation fix

data/language/pl-PL.txt
=> pl-PL: Apply #1929

data/language/es-ES.txt
=> es-ES: Apply #1929 #1887

data/language/es-ES.txt
=> es-ES: Apply #1888 #1903

data/language/pt-BR.txt
=> pt-BR: Apply #1942

data/language/eo-OO.txt
Applying for PR on main: #13096
=> Add Esperanto translation

data/language/eo-OO.txt
=> eo-OO: A few small fixes

data/language/pt-BR.txt
Accomodating for the string change in #1942
=> pt-BR: Ammend #1942

data/language/ko-KR.txt
=> ko-KR: Apply #1952

data/language/pt-BR.txt
=> pt-BR: Apply #1952

data/language/cs-CZ.txt
=> cs-cz apply #1952

data/language/eo-OO.txt
=> eo-OO: Revert modifier keys to English

data/language/eo-OO.txt
- #1960 
Also, translated some strings that were still in English
=> eo-OO: Apply #1960

data/language/eo-OO.txt
=> eo-OO: Apply #1952

data/language/ko-KR.txt
=> ko-KR: Apply #1966

data/language/pl-PL.txt
=> pl-PL: Apply #1942, #1952, #1966

data/language/de-DE.txt
=> de-DE: STR_0093, STR_0603, STR_6393

data/language/pt-BR.txt
=> PT-BR: Apply #1960 + #1966

data/language/ja-JP.txt
- #1446
I've translated "guest entry point" with 「ゲストのスポーンポイント」 (a transliteration of 'guest spawn point'). I think that captures it, right?
=> ja-JP: Apply #1446

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
=> Remove tr-TR from maintained languages

data/language/es-ES.txt
=> es-ES: Apply #1952 + #1960 + #1966

data/language/pt-BR.txt
- #1979
No change needed for `STR_2753`
=> pt-BR: Apply #1979

data/language/es-ES.txt
=> es-ES: Apply #1979

data/language/eo-OO.txt
=> eo-OO: Apply #1979

.github/workflows/translation_check.yml
Changed translation check action trigger in order to work around a lack of write access when executed on fork. Hopefully this does the trick.
=> Fix translation check action 

data/language/eo-OO.txt
- #1993 
Plus some translation refinements
=> eo-OO: Apply #1993

data/language/pt-BR.txt
=> pt-BR: Apply #1993

data/language/pl-PL.txt
Applying for issue: #1979
Hopefully translation check works as intended now.
=> pl-PL: Apply #1979

data/language/ko-KR.txt
Remove unused strings and Add missings to make the translation check numbers zero that added recently.
I've already seen https://github.com/OpenRCT2/Localisation/pull/2001, but please let me know if there is any problem :)
=> ko-KR: Apply #2005 and remove unused strings

data/language/de-DE.txt
=> de-DE: Apply #2005, #1993

.github/workflows/translation_check.yml
This should fix (or ad least improve) the situation in which a pull request is created from the fork master branch as described here #1998
=> Correctly handle pull requests from master branch

.github/workflows/translation_check.yml
Sorry about that! Thanks @tupaschoal for pointing this out!
=> Fixed typo on translation check

data/language/eo-OO.txt
=> eo-OO: Apply #2005

data/language/pl-PL.txt
=> [pl-PL] Apply #1993 and #2005

objects/eo-OO.json
- #2012 
Translations currently made to objects file for EO still a work in progress
=> eo-OO: Add current translations to objects file

objects/ko-KR.json
I hope this completes the object's translation :P
=> ko-KR: Complete object's translations

data/language/pt-BR.txt
=> pt-BR: Apply #2005

data/language/fr-FR.txt
- #1942 
- #1952 
- #1966 
- #1979 
- #1993 
- #2005
=> fr-FR: Apply #1942 #1952 #1966 #1979 #1993 #2005

data/language/pt-BR.txt
Using the new GH action, I found out some strings that were never translated in `pt-BR`
=> pt-BR: Translated some missing strings

data/language/hu-HU.txt
#1942
#1952
#1960
#1966
#1979
#1993
#2005
=> hu-HU: Apply #1942 #1952 #1960 #1966 #1979 #1993 #2005

data/language/it-IT.txt
- #1942
- #1952
- #1960
- #1966
- #1979
- #1993
- #2005
=> it-IT apply issues

data/language/es-ES.txt, objects/es-ES.json
=> es-ES: Apply #1993 , #2005

data/language/es-ES.txt, objects/es-ES.json
=> es-ES: Small translation fixes for json objects file.

data/language/es-ES.txt
=> es-ES: #2027 - STR_6398

data/language/pt-BR.txt
=> pt-BR: Apply #2027

data/language/pt-BR.txt
#2031 made me realise it was wrong from the beginning in `pt-BR`
=> Fix pt-br decimal and thousand separators

objects/pt-BR.json
=> pt-BR: Small adjustments to object translations

data/language/ko-KR.txt
=> ko-KR: Apply #2035

data/language/pt-BR.txt
=> pt-BR: Apply #2035

data/language/es-ES.txt
=> es-ES: Apply STR_6399

data/language/eo-OO.txt
=> eo-OO: Apply 6398-6399

objects/eo-OO.json
=> Update rct2.ww.killwhal to match with en-GB

objects/eo-OO.json
=> Translate some objects starting with letter A

data/language/eo-OO.txt
Renversi doesn't mean to reverse it means to turn upside-down, I'm silly.
=> eo-OO: Update some words

objects/eo-OO.json
https://github.com/OpenRCT2/Localisation/pull/2066 has the latest changes.
There is likely a merge conflict between this PR and 2066. Please accept the changes in 2066 for such conflicts.
=> eo-OO: Translate objects starting with letter M

objects/eo-OO.json
=> eo-OO: Translate objects starting with letter T, P & O

data/language/de-DE.txt
=> de-DE: STR_6398, STR_6399

objects/eo-OO.json
=> eo-OO: Translate objects starting with Sl to Sw

data/language/eo-OO.txt
Just noticed this smol typo before I go beb
=> eo-OO: Tweak Panda World description

data/language/eo-OO.txt
- Ellabori instead of disvolvi for physical development
- "Konverti/ellabori/transformi en" instead of "Konverti/disvolvi/transformi al"
=> eo-OO: Tweak strings

data/language/eo-OO.txt, objects/eo-OO.json
Also leave Robin Hood untranslated.
=> eo-OO: Tweak objects A to G

data/language/eo-OO.txt, objects/eo-OO.json
This finishes the proofreading of the EO files.
=> eo-OO: Tweak objects O to T

data/language/ca-ES.txt
- #1929
- #1942 
- #1952 
- #1966 
- #1960 
- #1979 
- #1993 
- #2027 
- #2035
- #2005 (partial. no objects translated)
=> ca-ES: Update translation

data/language/ko-KR.txt
=> ko-KR: Update scenario descriptions

data/language/ko-KR.txt
=> ko-KR: Apply #2104

data/language/fr-FR.txt
=> fr-FR: Apply #2027 #2035 #2104

data/language/pt-BR.txt
=> pt-BR: Apply #2104

data/language/fr-FR.txt
Some clean up and fixes not tied to a specific issue.
=> fr-FR: Cleanup

data/language/de-DE.txt
=> de-DE: STR_6400..STR_6409

data/language/eo-OO.txt
=> eo-OO: Apply #2104

data/language/eo-OO.txt
=> eo-OO: Apply #2111

data/language/es-ES.txt
=> es-ES: Apply #2111

data/language/pl-PL.txt
- #2027
- #2035 
- #2104 
- #2111
=> Added polish translations

data/language/es-ES.txt
=> es_ES: Apply #2104

data/language/de-DE.txt
=> de-DE: Apply #2111

data/language/de-DE.txt
This translates 4 more scenery strings to German.
=> de-DE: Add 4 more scenery strings

data/language/ko-KR.txt, objects/ko-KR.json
=> ko-KR: Apply #2121

data/language/de-DE.txt, objects/de-DE.json
=> de-DE: Replace ASCII apostrophes and backticks

data/language/pt-BR.txt, objects/pt-BR.json
=> pt-BR: Apply #2121

data/language/eo-OO.txt
=> eo-OO: Apply #2133

data/language/ko-KR.txt
=> ko-KR: Apply #2133

data/language/pt-BR.txt
=> pt-BR: Apply #2133

data/language/de-DE.txt, objects/de-DE.json
- #2133
Also fixes some bad translations in objects file.
=> de-DE: Apply #2133, fix some object translations

data/language/pt-BR.txt
=> pt-BR: Apply #2140

data/language/ko-KR.txt
=> ko-KR: Apply #2140 and misc.

data/language/eo-OO.txt
=> eo-OO: Apply #2140

data/language/pt-BR.txt
=> pt-BR: Apply #2144

data/language/eo-OO.txt
=> eo-OO: Apply #2144

data/language/de-DE.txt
=> de-DE: STR_6412-STR_6434

data/language/pt-BR.txt
=> pt-BR: Apply #2149

data/language/eo-OO.txt
=> eo-OO: Apply #2149

data/language/ko-KR.txt
I discovered this incorrect translation during translating guide pages of my website :(
=> ko-KR: Fix mistranslated strings

data/language/hu-HU.txt
#2027
#2035
#2104
#2111
#2121
#2133
#2140
#2144
#2149
=> hu-HU: Apply #2027 #2035 #2104 #2111 #2121 #2133 #2140 #2144 #2149

data/language/de-DE.txt
=> de-DE: Apply #2149

data/language/pt-BR.txt
=> pt-BR: Apply #2158

data/language/eo-OO.txt
=> eo-OO: Apply #2158

data/language/pl-PL.txt
- #2133
- #2140
- #2144
- #2149
- #2158
=> pl-PL: Applies #2133, #2140,#2144,#2149,#2158

data/language/pl-PL.txt, objects/pl-PL.json
=> pl-PL: Replace typewriter quotes

data/language/eo-OO.txt
=> eo-OO: Apply #2165

data/language/vi-VN.txt
Initial translations for vi-VN.
Still work in progress.
Please have a look at the issue with the character font/sprites.
=> vi-VN: Initial translations

data/language/de-DE.txt
=> de-DE: STR_6435-STR_6439

data/language/pt-BR.txt
=> pt-BR: Apply #2165

data/language/eo-OO.txt
=> eo-OO: Apply #2176

data/language/pt-BR.txt
=> pt-BR: Apply #2176

data/language/de-DE.txt
=> de-DE: Apply #2176

data/language/ko-KR.txt
=> ko-KR: Apply #2181

data/language/pt-BR.txt
=> pt-BR: Apply #2181

data/language/eo-OO.txt
=> eo-OO: Apply #2181

data/language/de-DE.txt
=> de-DE: Apply #2181

data/language/fr-FR.txt
- #2111
- #2133
- #2140
- #2144
- #2149
- #2158
- #2165
- #2176
- #2181
=> fr-FR: Apply #2111, #2133, #2140, #2144, #2149, #2158, #2165, #2176, #2181 and improve existing strings

data/language/pt-BR.txt
=> pt-BR: Apply #2188

data/language/eo-OO.txt
=> eo-OO: Apply #2188

data/language/fr-FR.txt
=> fr-FR: Apply #2188

data/language/it-IT.txt
- #2165
- #2176
- #2181
- #2188
=> it-IT: apply #2165,  #2176, #2181, #2188

data/language/fr-FR.txt
- All quotation marks replaced with guillemets
- Text that should be in italics put in small fonts
- Correct spaces around punctuation
- Correct capitalization
- Accents on uppercase characters
- Correct apostrophes
- Correct dashes
- Follow [translation guidelines](https://github.com/OpenRCT2/Localisation/wiki/Translator-guidelines:-fr_FR)
=> fr-FR: Improve translation

data/language/ko-KR.txt
1. It might mislead for some Korean that it is unable to demolish the rides/attractions (but can modify them). So I make it clearly.
2. Found un-unified phrases for transparent stations and fixed them
=> ko-KR: Improve some strings

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
Add myself as a maintainer for `fi-FI`, and for notifications in new/updated string issues.
=> Notify groenroos for fi-FI

data/language/nl-NL.txt
=> nl-NL: Apply #2188

data/language/de-DE.txt
=> de-DE: Apply #2188, #2199

data/language/fr-FR.txt
=> fr-FR: Apply #2199

data/language/fi-FI.txt
=> fi-FI: Apply #2199

data/language/eo-OO.txt
=> eo-OO: Apply #2199

data/language/fr-FR.txt
=> fr-FR: Apply #2205

data/language/pt-BR.txt
=> Apply #2199 and #2205

data/language/eo-OO.txt
=> eo-OO: Apply #2205

data/language/it-IT.txt
- #2199
- #2205
+ minor fixes to old translated strings
=> it-IT: apply #2199,  #2205 and other minor fixes

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
Hello,
It's been a very long time since I have not contributed to the french translation of OpenRCT2 and that is because my free time these days is getting shorter and I have to focus on other important things.
For these reasons, I prefer to step down as the "french localization maintainer" by "removing myself" from the notifications in issue templates and my name in the maintainer list. My place would be better suited for someone like @rmnvgr who contributed a lot these days by adding the missing strings but most importantly: fix the existing translation. Something I wanted to do months ago but time never allowed me to focus on that.
Thank you for allowing me to contribute to this amazing project. Translating OpenRCT2 and programming the initial [keyboard shortcuts for track …
=> fr-FR: stepping down as maintainer

data/language/de-DE.txt
=> de-DE: STR_6456

data/language/fr-FR.txt
- #2214
I could have translated "bug" (which is fine in French) by "dysfonctionnement" but that would have made the menu item disproportionately long compared to the others.
=> fr-FR: Apply #2214

data/language/eo-OO.txt
=> eo-OO: Apply #2214

data/language/fi-FI.txt
=> fi-FI: Apply #2205, #2214

data/language/pt-BR.txt
=> pt-BR: Apply #2214

data/language/pt-BR.txt
=> pt-BR: Apply #2220

data/language/fr-FR.txt
=> fr-FR: Apply #2220

data/language/eo-OO.txt
=> eo-OO: Apply #2220

data/language/de-DE.txt
=> de-DE: Apply #2220, #2214

data/language/de-DE.txt
I have made a terrible mistake! I accidentally put in the incorrect string ID in my previous PR. This will fix it.
Whoops!
=> de-DE: Fix incorrect string ID

data/language/es-ES.txt
=> es-ES:  Apply #2199

data/language/it-IT.txt
- #2214
- #2220
+ other minor fixes
=> it-IT apply #2214, #2220 and other fixes

data/language/da-DK.txt
Fixes some typos, finalizing Scenarios descriptions.
100% DONE
and
- #2176 
- #2181 
- #2188 
- #2199 
- #2205 
- #2214 
- #2220
=> da-DK: Update scenario descriptions and apply #2176, #2181, #2188, #2199, #2205, #2214, #2220

data/language/hu-HU.txt
- #2158
- #2165
- #2176
- #2181
- #2188
- #2199
- #2205
- #2214
- #2220
=> hu-HU: Apply #2158, #2165, #2176, #2181, #2188, #2199, #2205, #2214, #2220

data/language/es-ES.txt
=> es-ES: Apply #2243

data/language/eo-OO.txt
=> eo-OO: Apply #2243

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
I've been working on the French translation for a long time but never added myself as a maintainer, this PR fixes that.
=> fr-FR: Add rmnvgr as maintainer

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2251

data/language/pt-BR.txt
=> pt-BR: Apply 2243-2251

data/language/es-ES.txt
=> es-ES: Apply #2251 string 3189

data/language/de-DE.txt
=> de-DE: Apply #2243, #2251

data/language/es-ES.txt
- #1675
- #1755
- #1773
- #1781
- #1789
- #1795
- #1809
- #1821
- #1826
- #1858
- #1876
- #1952
- #1960
- #1966
- #1993
- #2005
- #2121
- #2133
- #2140
- #2181
- #2188
=> Multiple translations, also retrying to get issues marked as complete.

data/language/es-ES.txt, data/language/pt-BR.txt
=> Fixed all clearance mentions and added 2 missing translations

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2264

data/language/es-ES.txt
=> es-ES: Apply #2264

data/language/pt-BR.txt
=> pt-BR: Apply #2264

data/language/fr-FR.txt
=> fr-FR: Apply #2264

data/language/pl-PL.txt
Apply for:
- #2165
- #2176
- #2181
- #2188
- #2199
- #2205
- #2214
- #2220
- #2243
- #2251
- #2264
- deleted unused translations
- reviewed and updated some strings
=> Add missing pl-PL translations

data/language/sv-SE.txt
No issue, just noticed while playing
=> sv-SE: fix typo

data/language/sv-SE.txt
=> sv-SE: apply #2243, #2251, #2264

data/language/it-IT.txt
=> it-IT: Apply #2264

data/language/ko-KR.txt
=> ko-KR: Apply #2278

data/language/pt-BR.txt
=> pt-BR: Apply #2278

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2284 & #2286

data/language/es-ES.txt
=> es-ES: Apply #2284

data/language/es-ES.txt
=> es-ES: Apply #2286

data/language/pt-BR.txt
=> pt-BR: Apply #2286

data/language/fr-FR.txt
This is a proposal for an improvement of the translation for `X is really good value`.
The current translation sounds awkward to me (that's personal taste) but more importantly in my view it doesn't convey what this guest's thought is really about: pricing. `X est un très bon choix` sounds to me like the relative quality of the thing is good, but I don't know what is good about it.
`X est vraiment une bonne affaire` is more clearly about the price which would make it a more easily actionable input for the player.
An alternative would be `X est vraiment bon marché`. What would sound most natural to me would be `X est vraiment pas cher` but then you'd have to know what it is to choose between `cher / chère / chers / chères` and there's no way to know what players name their rides.
=> [fr-FR] Improve translation for 'good value'

data/language/es-ES.txt
=> es-ES: Apply #2294

data/language/pt-BR.txt
=> pt-BR: Apply #2294

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2294

data/language/es-ES.txt
=> es-ES: Apply #2300

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2300

data/language/fr-FR.txt
=> fr-FR: Apply #2300

data/language/pt-BR.txt
=> pt-BR: Apply #2300

data/language/de-DE.txt
- #2300
- #2294
- #2286
- #2284
- #2278
- #2264
=> de-DE: Translate STRs 6371, 6437, 6438, 6462-6488

data/language/fr-FR.txt
- https://github.com/OpenRCT2/OpenRCT2/issues/16982
=> OpenRCT2/16982 - Fr fix dup msg for on inability to increase park loan

data/language/pl-PL.txt
Apply:
- #2278
- #2284
- #2286
- #2294
- #2300
=> pl-PL: Apply: #2278, #2284, #2286, #2294, #2300

data/language/fr-FR.txt
=> fr-FR: Apply #2311

data/language/nl-NL.txt
=> nl-NL: Apply #2311

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2311

data/language/pt-BR.txt
=> pt-BR: Apply #2311

data/language/es-ES.txt
=> es-ES: Apply #2311

data/language/de-DE.txt
=> de-DE: Apply #2311

data/language/zh-TW.txt
By reviewing the checks, I found out that there is an issue missed from previous updates. This PR fixes it. :)
- #1916
=> zh-TW: Apply #1916

data/language/es-ES.txt
=> es-ES: Apply #2327 #2328

data/language/fr-FR.txt
=> fr-FR: Apply #2327 and #2328

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2327 & #2328

data/language/pt-BR.txt
=> pt-BR: Apply #2327 & 2328

data/language/ca-ES.txt
Some fixes and applying for several issues.
Sorry for applying for so many issues in a single PR.
**Please, revise PR and commit messages and squash the commits if necessary.**
Thank you!
- #2104 
- #2111 
- #2133 
- #2140 
- #2144 
- #2149 
- #2158 
- #2165 
- #2264 
- #2176 
- #2181 
- #2188 
- #2199 
- #2205 
- #2214 
- #2220 
- #2243 
- #2251 
- #2278 
- #2284 
- #2286 
- #2294 
- #2300 
- #2311 
- #2327 
- #2328
=> ca-ES: Some fixes and applying for several issues.

data/language/zh-CN.txt
Fix some translations error I just find out.
=> zh-CN: Fix some error

objects/ca-ES.json
This PR provides ~50 % of the object strings translated into Catalan.
=> ca-ES: Provide Catalan localisation for several objects.

data/language/ca-ES.txt, objects/ca-ES.json
This PR amends some strings in Catalan. It also completes the localisation of objects, started in #2338.
=> ca-ES: Amend some strings and provide localisation for objects. 

data/language/it-IT.txt
- #2278 
- #2284 
- #2286 
- #2294 
- #2300 
- #2311 
- #2327 
- #2328 
- some fixes to related strings
- fixed every suggestion by Translation Check
=> it-IT: New strings and fixes

data/language/pl-PL.txt
=> pl-PL: Apply #2345

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2345

data/language/de-DE.txt, data/language/nl-NL.txt
Rodelbaan.
Laat me even weten of dit een goede zin is, maar volgens mij is dit prima. 
Of zal ik er "door te remmen" erbij zetten? Denk ik onnodig.
I have also added the coaster translation for German (`de-DE`) since it's incredibly similar to Dutch (Rodelbahn), but my German is too poor to make a correct sentence.
=> nl-NL: Add translation for Alpine Coaster

data/language/fr-FR.txt
=> fr-FR: Apply #2345

data/language/es-ES.txt
- #2345 
> +Also changed a capital letter for consistency
=> es-ES: Apply #2345

data/language/de-DE.txt
=> de-DE: Apply #2345, #2328, #2327

data/language/fr-FR.txt
=> fr-FR: Apply #2354

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2354

data/language/es-ES.txt
=> es-ES: Apply #2354

data/language/fi-FI.txt
- #2220
- #2243
- #2251
- #2264
- #2278
- #2284
- #2286
- #2294
- #2300
- #2311
- #2327
- #2328
- #2345
- #2354
=> fi-FI: Update

data/language/pt-BR.txt
=> pt-BR: Apply 2345-2354

data/language/it-IT.txt
=> it-IT apply #2354

data/language/pt-BR.txt
=> pt-BR: Apply #2363

data/language/fr-FR.txt
=> fr-FR: Apply #2363

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2363

data/language/es-ES.txt
=> es-ES: Apply #2363

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2369

data/language/pt-BR.txt
=> pt-BR: Apply #2369

data/language/es-ES.txt
=> es-ES: apply #2369

data/language/fr-FR.txt
=> fr-FR: Apply #2369

data/language/de-DE.txt
=> de-DE: Apply #2369, #2363, #2369

data/language/fr-FR.txt
=> fr-FR: Apply #2378

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2378

data/language/es-ES.txt
=> es-ES: Apply #2378

data/language/pt-BR.txt
=> pt-BR: Apply #2378

data/language/de-DE.txt
- #2378
- #2386
- #2387
- #2388
=> de-DE: Apply #2378, #2386, #2387, #2388

data/language/pl-PL.txt
- #2354, 
- #2363 
- #2369 
- #2378 
- #2386 
- #2387 
- #2388
=> pl-PL: Apply #2354, #2363, #2369, #2378, #2386, #2387, #2388

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2386, #2387, #2388

data/language/pt-BR.txt
=> pt-BR: Apply #2399

data/language/pl-PL.txt
=> pl-PL: Apply #2399 (and fix grammar in similar strings)

data/language/de-DE.txt
=> de-DE: Apply #2399

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2399

data/language/fr-FR.txt
- #2386
- #2387
- #2388 
- #2399
=> fr-FR: Apply #2386, #2387, #2388, #2399

data/language/es-ES.txt
=> es-ES: Apply #2399 #2387 (consistent translation)

data/language/ca-ES.txt, objects/ca-ES.json
Some strings amended are in the objects repo.
- #2345
- #2354
- #2363 
- #2369 
- #2378 
- #2386 
- #2387 
- #2388
- #2399
=> ca-ES: Amend some strings and applying for several issues.

data/language/es-ES.txt
=> es-ES: Apply #2388

data/language/pt-BR.txt
=> pt-BR: Apply #2414

data/language/es-ES.txt
- #2386
> Also made consistent (left) (right) in spanish across strings
=> es-ES: Apply #2386 + few consistency changes

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2414

data/language/ca-ES.txt
=> ca-ES: Apply #2414

data/language/es-ES.txt
- #2414
> Made some strings under RTC2 scenarios consistent with en-GB (removing " - " for simple dots).
> Also fixed some non stressed words ("más"), missing "¡" and two too literal words ("repagar", "remueve").
=> es-ES: Apply #2414 + some fixes

objects/eo-ZZ.json
Added new translations to objects file, plus several other fixes and additions.
=> eo-ZZ: Update objects file

data/language/fr-FR.txt
=> fr-FR: Apply #2414

data/language/it-IT.txt
This fixes some typos or strings that were too long in the it-IT translation.
=> it-IT fixes

data/language/nb-NO.txt
When checkboxes have been checked I'll do a pass to see which issues I missed or skipped :)
- #1745
- #1755
- #1773
- #1781
- #1786
- #1789
- #1795
- #1804
- #1809
- #1813
- #1821
- #1826
- #1844
- #1847
- #1850
- #1858
- #1862
- #1866
- #1876
- #1887
- #1888
- #1898
- #1903
- #1916
- #1917
- #1929
- #1942
- #1952
- #1960
- #1966
- #1979
- #1993
- #2005
- #2027
- #2035
- #2104
- #2111
- #2133
- #2140
- #2144
- #2149
- #2158
- #2165
- #2176
- #2181
- #2188
- #2199
- #2205
- #2214
- #2220
- #2243
- #2251
- #2264
- #2284
- #2286
- #2294
- #2300
- #2311
- #2327
- #2328
- #2345
- #2354
- #2363
- #2369
- #2378
- #2386
- #2387
- #2388
- #2399
- #2414
=> nb-NO catchup 2022-08

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2430

data/language/fr-FR.txt
=> fr-FR: Apply #2430

data/language/it-IT.txt
STR_6474 and STR_6475 are good as they are + Fixed STR_6484 and STR_6485 (before #2363 it was ambiguous, maybe also in english should be changed to match #2363).
- #2399
- #2345
- #2363
- #2430
=> it-IT: Apply #2399, #2345, #2363, #2430 + Fix STR_6484 and STR_6485

data/language/de-DE.txt
=> de-DE: Apply #2430, #2414

data/language/ca-ES.txt
=> ca-ES: Apply for #2430

data/language/hu-HU.txt
- #2243
- #2251
- #2264
- #2278
- #2284
- #2286
- #2294
- #2300
- #2311
- #2327
- #2328
- #2345
- #2363
- #2369
- #2378
- #2386
- #2387
- #2388
- #2399
=> hu-HU: Apply #2243 #2251 #2264 #2278 #2284 #2286 #2294 #2300 #2311 #2327 #2328 #2345 #2363 #2369 #2378 #2386 #2387 #2388 #2399

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2446

data/language/ar-EG.txt, data/language/ca-ES.txt, data/language/da-DK.txt, data/language/de-DE.txt, data/language/eo-ZZ.txt, data/language/es-ES.txt, data/language/fi-FI.txt, data/language/fr-FR.txt, data/language/hu-HU.txt, data/language/it-IT.txt, data/language/ja-JP.txt, data/language/ko-KR.txt, data/language/nl-NL.txt, data/language/pl-PL.txt, data/language/pt-BR.txt, data/language/sv-SE.txt, data/language/tr-TR.txt, data/language/vi-VN.txt, data/language/zh-CN.txt
Following up on: https://github.com/OpenRCT2/OpenRCT2/commit/429433bf4f31a47a1dea630aba21004b4abf498d
=> Remove obsolete TTRFGL translations from non-object file

data/language/pt-BR.txt
=> pt-BR: Apply #2430, #2446

data/language/hu-HU.txt
=> hu-HU: Apply #2446

data/language/sv-SE.txt
=> sv-SE: Apply #2284

data/language/es-ES.txt
=> es-ES: Apply #2446

data/language/sv-SE.txt
=> sv-SE: Apply #2286, #2294, #2363

data/language/sv-SE.txt
=> sv-SE: Apply #2300, #2311

data/language/de-DE.txt
=> de-DE: Apply #2446

data/language/es-ES.txt
* Took a look and found some common errors with Spanish accents, both cases exist but mean a different things (e.g. más, está).
* And also found some varied missing accent errors.
cheers
=> es-ES: fix common Spanish accent errors

data/language/ar-EG.txt
=> String 1367

data/language/it-IT.txt
- #2399
- #2414
- #2430
- #2446
+ some proofreading of old strings.
=> it-IT fixes and new translations

data/language/es-ES.txt
=> es-ES: Apply #2466

data/language/de-DE.txt
- #2466
Fixes https://github.com/OpenRCT2/OpenRCT2/issues/18264
=> de-DE: Apply #2466

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2466

data/language/hu-HU.txt
=> hu-HU: Apply #2466

data/language/pt-BR.txt
=> pt-BR: Apply #2466, #2472, #2473

data/language/hu-HU.txt
=> hu-HU: Apply #2472, #2473 + a few small fixes

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2472, #2473

data/language/fr-FR.txt
=> fr-FR: Apply #2466, #2472, #2473

data/language/da-DK.txt
=> da-DK: apply #2472 #2473

data/language/tr-TR.txt
Added translated version of string 6527
- #6527
=> tr-TR : String 6520-6527 

data/language/tr-TR.txt
=> tr-TR :  #2466 #2446

data/language/da-DK.txt
- #2446 
- #2430 
- #2399 (changed)
- #2386 
- #2369 
- #2354  
- #2328
=> Update da-DK.txt Apply #2446 #2430 #2399 #2386 #2369 #2354 #2328

data/language/ca-ES.txt
=> ca-ES: Apply #2466, #2472, #2473 and amend some strings

data/language/cs-CZ.txt, objects/cs-CZ.json
I've seen this project recently with cs-CZ being little bit behind. I would like to start slowly bringing it up to date.
- #1960 
- #1966 
- #1979 
- #1993 
- #2005
=> cs-CZ: Apply #1960, #1966, #1979, #1993, #2005

data/language/cs-CZ.txt
- #2243
- #2220
- #2214
- #2205
- #2199
- #2188
- #2181
- #2176
- #2165
- #2158
- #2149
- #2144
- #2140
- #2133
- #2121
- #2111
- #2104
- #2035
- #2027
=> cz-CS second update for cz lang

data/language/tr-TR.txt
=> Tr ceviri #2430  #2414 

data/language/hu-HU.txt
=> hu-HU: Apply #2492

data/language/fr-FR.txt
=> fr-FR: Apply #2492

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2492

data/language/ko-KR.txt
=> ko-KR: Apply #2492

data/language/es-ES.txt
=> es-ES: Apply #2492

data/language/cs-CZ.txt
cs-CZ: Apply #2492
cs-CZ: Apply #2473
cs-CZ: Apply #2472
cs-CZ: Apply #2446
cs-CZ: Apply #2430
cs-CZ: Apply #2414
cs-CZ: Apply #2399
cs-CZ: Apply #2388
cs-CZ: Apply #2387
cs-CZ: Apply #2386
cs-CZ: Apply #2378
cs-CZ: Apply #2369
cs-CZ: Apply #2363
cs-CZ: Apply #2354
cs-CZ: Apply #2345
cs-CZ: Apply #2328
cs-CZ: Apply #2327
cs-CZ: Apply #2311
cs-CZ: Apply #2300
cs-CZ: Apply #2294
cs-CZ: Apply #2286
cs-CZ: Apply #2284
cs-CZ: Apply #2278
cs-CZ: Apply #2264
cs-CZ: Apply #2251
=> Updating cs-CZ

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2501

data/language/pt-BR.txt
=> pt-BR: Apply #2501

data/language/fr-FR.txt
=> fr-FR: Apply #2501

data/language/hu-HU.txt
=> hu-HU: Apply #2501

data/language/es-ES.txt
=> es-ES: apply #2501

data/language/ko-KR.txt
- #2509 
I decided to translate ``STR_6530`` as I commented at [#2509.](https://github.com/OpenRCT2/Localisation/issues/2509#issuecomment-1324925260)
(btw, UCES is not very known in South Korea)
=> ko-KR: Apply #2509

data/language/de-DE.txt
* #2472
* #2473
* #2492
* #2509
* #2511
=> de-DE: Apply #2472, #2473, #2492, #2509, #2511

data/language/hu-HU.txt
=> hu-HU: Apply #2509, #2511

data/language/fr-FR.txt
=> fr-FR: Apply #2509, #2511

data/language/es-ES.txt
=> es-ES: Apply #2511

data/language/es-ES.txt
=> es-ES: Apply #2509

data/language/pt-BR.txt
=> pt-BR: Apply #2511

data/language/pt-BR.txt
=> pt-BR: Apply #2509 & #2520

data/language/hu-HU.txt
=> hu-HU: Apply #2520 + some fixes

data/language/fr-FR.txt
=> fr-FR: Apply #2520

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2509 #2511 #2520

data/language/fr-FR.txt
=> fr-FR: Apply #2527

data/language/pt-BR.txt
- #2527
I already took into consideration some of the comments made in the original PR that introduced/changed the strings.
=> pt-BR: Apply #2527

data/language/de-DE.txt
=> de-DE: Apply #2520 and #2527

data/language/hu-HU.txt
=> hu-HU: Apply #2527

data/language/es-ES.txt
- #2527: also modified `STR_6492` to add a "v" before the version number for consistency with the new strings.
cheers!
=> es-ES: Apply #2527

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2527

data/language/zh-CN.txt
- #2492 
- #2501 
Minor changes:
Add some ‘{NEWLINE}’ In some lines which been used in New Games window to make sure that string display well on all Fonts.
=> zh-CN: Apply #2492 #2501 + Some minor changes

data/language/ko-KR.txt
=> ko-KR: Apply #2535

data/language/hu-HU.txt
=> hu-HU: Apply #2535 + fixes

data/language/ca-ES.txt
- #2492
- #2501 
- #2509 
- #2511 
- #2520 
- #2527 
- #2535
=> ca-ES: Apply #2492 #2501 #2509 #2511 #2520 #2527 #2535 + some fixes

data/language/es-ES.txt
=> es-ES: Apply #2535

data/language/pt-BR.txt
=> pt-BR: Apply #2535

data/language/fr-FR.txt
=> fr-FR: Apply #2535

data/language/de-DE.txt
=> de-DE: Apply #2535

data/language/ko-KR.txt
=> ko-KR: Apply #2550, 2551

data/language/pt-BR.txt
=> pt-BR: Apply #2550-#2551

data/language/ca-ES.txt
=> ca-ES: Apply #2550 #2551

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2535 #2550 #2551

data/language/fr-FR.txt
- #2550
- #2551
I also updated string 6319 since the translation was incorrect.
=> fr-FR: Apply #2550, 2551

data/language/zh-CN.txt
- #2509 
- #2511 
- #2520 
- #2527 
- #2535 
- #2550 
- #2551
=> zh-CN: Apply Issues  #2509 #2511 #2520 #2527 #2535 #2550 #2551 

data/language/pt-BR.txt
=> pt-BR: Apply #2558, #2562, #2563

data/language/ko-KR.txt
- #2558 
- #2562 
- #2563 
note) I'll not translate Tycoon Park's ``STR_SCNR``
=> ko-KR: Apply #2558, #2562, #2563

data/language/fr-FR.txt
=> fr-FR: Apply #2562, #2563

data/language/es-ES.txt
=> es-ES: apply #2551, #2550

data/language/es-ES.txt
=> es-ES: apply #2558, #2562, #2563

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2558 #2562 #2563

data/language/de-DE.txt
- #2562
- #2550
- #2563
- #2551
- #2558
=>  de-DE: Apply #2562, #2550, #2563, #2551, #2558 

data/language/fr-FR.txt
=> fr-FR: Apply #2572

data/language/nl-NL.txt
- #2558
- #2562
- #2563
- #2572
=> nl-NL: Apply #2558, #2562, #2563, #2572

data/language/es-ES.txt
=> es-ES: Apply #2572

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2572

data/language/pt-BR.txt
=> pt-BR: Apply #2578

data/language/nl-NL.txt
=> nl-NL: Apply #2578

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2578

data/language/fr-FR.txt
=> fr-FR: Apply #2578

data/language/hu-HU.txt
- #2550
- #2551
- #2558
- #2562
- #2563
- #2572
- #2578
=> hu-HU: Apply #2550, #2551, #2558, #2562, #2563, #2572, #2578

data/language/es-ES.txt
=> es-ES: Apply #2578

data/language/de-DE.txt
- #2572
- #2578
Also adds STR_6530, which was missing (see #2509).
=> de-DE: Apply #2572, #2578, add STR_6530

data/language/pt-BR.txt
=> pt-BR: Apply #2594

data/language/pt-BR.txt
=> pt-BR: Apply #2602

data/language/ca-ES.txt
=> ca-ES: Apply #2602

data/language/fr-FR.txt
=> fr-FR: Apply #2602

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2602

data/language/pt-BR.txt
=> pt-BR: Apply #2609

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2609

data/language/fr-FR.txt
Hello! I read the whole fr-FR.txt file from beginning to end and fixed a few problems, ranging from typos to missing translations and a few suggested improvements. I have tried to separate them in different commits so it's easier to review. Let me know if you have any questions! Thanks!
=> fr-FR: Various improvements

data/language/es-ES.txt
=> es-ES: Apply #2594, #2602

data/language/nl-NL.txt
- #2594
- #2602
- #2609
- #2620
=> nl-NL: Apply #2594, #2602, #2609, #2620

data/language/pt-BR.txt
=> pt-BR: Apply #2625

data/language/fr-FR.txt
=> fr-FR: Apply #2609, #2620, #2625

data/language/nl-NL.txt
=> nl-NL: Apply #2625, fix STR_6579

data/language/eo-ZZ.txt
- #2620 
- #2625 
Plus a small word fix
=> eo-ZZ: Apply #2620 , #2625

data/language/pt-BR.txt
=> pt-BR: Apply #2631

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2631

data/language/es-ES.txt
=> es-ES: Apply #2620

data/language/nl-NL.txt
=> nl-NL: Apply #2631

data/language/es-ES.txt
=> es-ES: Apply #2625, #2631

data/language/de-DE.txt
=> de-DE: Apply #2609

data/language/fr-FR.txt
Applying for issue(:
- #2631
Also add missing space from previous translation.
=> fr-FR: Apply #2631

data/language/pt-BR.txt
=> pt-BR: Apply #2641

data/language/nl-NL.txt
=> nl-NL: Apply #2641

data/language/es-ES.txt
=> es-ES: Apply #2641

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2641

data/language/ca-ES.txt
- #2609 
- #2620 
- #2625 
- #2631 
- #2641
=> ca-ES: Apply #2609, #2620, #2625, #2631, #2641

data/language/de-DE.txt
- #2594
- #2602
- #2620
- #2625
- #2631
- #2641
This PR also changes a few translations for the new colors because some translations were slighly confusing/misleading.
=> de-DE: Update stirngs from 6548 to 6585

data/language/it-IT.txt
I've been busy and I still have to catch up with many issues, but in the meantime...
- #2466
- #2472
- #2473
- #2492
- #2501
- #2509
=> it-IT translations

data/language/ko-KR.txt
=> ko-KR: Apply #2650

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2650

data/language/es-ES.txt
=> es-ES: Apply #2650

data/language/fr-FR.txt
=> Apply 2641, 2650

data/language/pt-BR.txt
=> pt-BR: Apply #2650, #2658, #2659

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2658 #2659

data/language/nl-NL.txt
=> nl-NL: Apply #2658, #2659

data/language/es-ES.txt
=> es-ES: Apply #2658

data/language/fr-FR.txt
=> fr-FR: Apply #2658, #2659

data/language/de-DE.txt
- #2659
- #2658
- #2650 
My commit for the contributors file takes place in this PR: https://github.com/OpenRCT2/OpenRCT2/pull/20552
=> de-DE: Update strings from 6586 to 6592

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
Add myself as de-DE maintainer, so I get informed when there is something to translate
=> de-DE: Add gr33ndev as maintainer

data/language/ca-ES.txt
=> ca-ES: Apply #2650, #2658, #2659

data/language/hu-HU.txt
- #2602
- #2609
- #2620
- #2625
- #2631
- #2641
- #2650
- #2658
- #2659
=> hu-HU: Apply #2602, #2609, #2620, #2625, #2631, #2641, #2650, #2658, #2659

data/language/it-IT.txt
Just some it-IT translation quality improvements.
I changed some phrases to make them fit inside of the constrained windows (some text was overflowing).
=> Quality improvements it-IT

data/language/it-IT.txt
=> it-IT: apply #2678, #2679

data/language/pt-BR.txt
=> pt-BR: Apply #2678, #2679

data/language/hu-HU.txt
=> hu-HU: Apply #2678, #2679

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2678 #2679

data/language/de-DE.txt
=> de-DE: apply #2678, #2679

data/language/pt-BR.txt
=> pt-BR: Apply #2692

data/language/it-IT.txt
=> it-IT: apply #2692

data/language/hu-HU.txt
=> hu-HU: Apply #2692

data/language/nl-NL.txt
=> nl-NL: Apply #2678, #2679, #2692

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2692

data/language/de-DE.txt
=> de-DE: Apply #2692

data/language/de-DE.txt
use same vocabulary as STR_6537
=> de-DE: Improve consistency in STR_6538

data/language/pt-BR.txt
=> pt-BR: Apply #2709

data/language/en-US.txt
The description for the scenario Inca Lost City states there is a height restriction. Since there is no such restriction, I've opted to remove the statement from the scenario description.
EDIT (by @tupaschoal):
- #2709
=> en-US: Apply #2709

data/language/hu-HU.txt
=>  hu-HU: Apply #2709 + fixes, improvements and new translations 

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2709

data/language/de-DE.txt
=> de-DE: Apply #2709

data/language/it-IT.txt
=> it-IT: apply #2720 and #2709

data/language/eo-ZZ.txt
- #2720 
Plus small typo fix for STR_6478
=> eo-ZZ: Apply #2720

data/language/de-DE.txt
=> de-DE: apply #2720

data/language/pt-BR.txt
=> pt-BR: Apply #2720

data/language/fr-FR.txt
- #2678
- #2679
- #2692
- #2709
- #2720
=> fr-FR: Apply #2678, #2679, #2692, #2709, #2720

data/language/nb-NO.txt
Translated from STR_1473 to STR_1654
- #0000
- #0001
=> Continued translation. nb-NO.txt

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2732

data/language/pt-BR.txt
=> pt-BR: Apply #2732

data/language/hu-HU.txt
=> hu-HU: Apply #2732 + small fixes

objects/pt-BR.json
Translating all missing object strings on pt-br
=> pt-BR: Translate missing object strings

data/language/it-IT.txt
=> it-IT: apply #2732

data/language/es-ES.txt
=> es-ES: Apply #2720,#2732

data/language/ca-ES.txt
- #2678 
- #2679 
- #2692 
- #2709 
- #2720 
- #2732
=> ca-ES: Apply #2678, #2679, #2692, #2709, #2720, #2732

objects/hu-HU.json
=> hu-HU: Apply OpenRCT2#2748 + object file translation part 1

data/language/fi-FI.txt
- #2732
- #2720
- #2709
- #2692
- #2679
- #2678
- #2659
- #2658
- #2650
- #2641
- #2631
- #2625
- #2620
- #2609
- #2602
- #2594
- #2578
- #2572
- #2563
- #2562
- #2558
- #2551
- #2550
- #2535
- #2527
- #2520
- #2511
- #2509
- #2501
- #2492
- #2473
- #2472
- #2446
- #2466 (no-op, covered in #2511)
- #2430
- #2414
- #2399
- #2388
- #2387
- #2386
- #2378
- #2369
- #2363
=> fi-FI: Bring strings up to date

data/language/fr-FR.txt
=> fr-FR: Apply #2732

objects/es-ES.json
=> es-ES: Apply #2748

data/language/fr-FR.txt, objects/fr-FR.json
- Translate missing object name and description
- Correct some errors
- Make everything more consistent
=> fr-FR: Translate remaining objects and fix inconsistencies

data/language/nb-NO.txt
=> nb-NO: Apply #2755

data/language/eo-ZZ.txt
- #2755 
Plus small change to another string for consistency
=> eo-ZZ: Apply #2755

data/language/pt-BR.txt
=> pt-BR: Apply #2755

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
@CsyeCokTheSolly I'm adding `uk-UA` as an active language. Let us know if you want us to add you to the issue notification whenever a new string is added, or if you'd rather wait until the translation is finished.
=> uk-UA: Add as maintained language and track on issues

data/language/it-IT.txt
=> it-IT: apply #2755

data/language/ca-ES.txt, objects/ca-ES.json
=> ca-ES: Apply #2755 and translate missing objects

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2769

data/language/hu-HU.txt
=> hu-HU: Apply #2769 + corrections

data/language/pt-BR.txt
=> pt-BR: Apply #2769

data/language/fr-FR.txt
=> fr-FR: Apply #2755 and #2769

objects/ko-KR.json
- #2781
I left ``reference-name`` as is
=> ko-KR: Apply #2781

objects/pt-BR.json
=> pt-BR: Apply #2781

objects/hu-HU.json
=> hu-HU: Apply #2781 + object file translation part 2

objects/es-ES.json
- #2781
- Ammend a few strings for consistency
=> es-ES: Apply #2781 + ammends

objects/eo-ZZ.json
=> eo-ZZ: Apply #2781

data/language/nb-NO.txt
=> nb-NO: Apply #2769

data/language/de-DE.txt, objects/de-DE.json
- #2732
- #2755
- #2769
- #2781
=> de-DE: Apply #2732, #2755, #2769, #2781

data/language/es-ES.txt
=> es-ES: Apply #2755, #2769

data/language/es-ES.txt
=> es-ES: Apply #2794

data/language/hu-HU.txt
=> hu-HU: Apply #2794 + corrections 

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2794

data/language/pt-BR.txt
=> pt-BR: Apply #2794, #2801

data/language/es-ES.txt
=> es-ES: Apply #2801

data/language/hu-HU.txt
=> hu-HU: Apply #2801, #2806

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2801 #2806

.github/ISSUE_TEMPLATE/changed_field_template.md, .github/ISSUE_TEMPLATE/new_and_changed_field_template.md, .github/ISSUE_TEMPLATE/new_field_template.md, README.md
- None
Add myself to the maintainers' list.
=> zh-CN: add mrmagic2020 to maintainers list

data/language/es-ES.txt
=> es-ES: Apply #2806

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2814 #2815

data/language/hu-HU.txt
=> hu-HU: Apply #2814, #2815

data/language/pt-BR.txt
=> pt-BR: Apply #2814, #2815

data/language/hu-HU.txt
=> hu-HU: Apply #2826

data/language/it-IT.txt
=> it-IT: Apply #2801, #2769, #2794

data/language/de-DE.txt
=> de-DE: apply #2843

data/language/pt-BR.txt
=> pt-BR: Apply #2843

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2843

data/language/hu-HU.txt
=> hu-HU: Apply #2836, #2843

data/language/hu-HU.txt
=> hu-HU: Apply #2821 + fixes

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2854

data/language/ko-KR.txt
=> ko-KR: Apply #2854

data/language/pt-BR.txt
=> pt-BR: Apply #2854

data/language/es-ES.txt
=> es-ES: Apply #2854

data/language/hu-HU.txt
=> hu-HU: Apply #2854

data/language/de-DE.txt
=> de-DE: apply #2854

data/language/ca-ES.txt
- #2769
- #2794 
- #2801 
- #2806 
- #2814 
- #2815 
- #2821 
- #2826 
- #2836 
- #2843 
- #2854
=> ca-ES: Apply #2769, #2794, #2801, #2806, #2814, #2815, #2821, #2826, #2836, #2843 and #2854

objects/ca-ES.json
Thanks for fixing the json file for Catalan some months ago!
- #2781
=> ca-ES: Apply #2781

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2868 #2869

data/language/pt-BR.txt
- #2868
- https://github.com/OpenRCT2/Localisation/issues/2869
=> pt-BR: Apply #2868, #2869

data/language/ko-KR.txt
=> ko-KR: Apply #2868, #2869

data/language/es-ES.txt
- #2868
- #2869 > ups mentioned twice in the commit (amended it)
=> es-ES: Apply #2868, #2869

data/language/de-DE.txt
=> de-DE: apply #2868, #2869 & #2875

data/language/pt-BR.txt
=> pt-BR: Apply #2875

data/language/es-ES.txt
=> es-ES: Apply #2875

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2875

data/language/hu-HU.txt
=> hu-HU: Apply #2868, #2869, #2875

data/language/eo-ZZ.txt
- #2884 
Plus a couple grammar fixes for 3D Cinema strings
=> eo-ZZ: Apply #2884 + grammar fixes

data/language/es-ES.txt
=> es-ES: Apply #2881, #2884

data/language/ca-ES.txt
- #2868 
- #2869 
- #2875 
- #2881 
- #2884
=> ca-ES: Apply #2868, #2869, #2875, #2881, #2884

data/language/de-DE.txt
=> apply #2881, #2884 to de-DE

data/language/hu-HU.txt
=> hu-HU: Apply #2881, #2884

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2894 #2895 #2897

data/language/fr-FR.txt
- #2836
- #2843
- #2854
- #2868
- #2869
- #2875
- #2881
- #2884
- #2894
- #2895
- #2897
=> fr-FR: Add missing translations

data/language/pt-BR.txt
=> pt-BR: Apply #2894, #2895, #2897

data/language/it-IT.txt
- #2869
- #2868
- #2875
- #2881 
- #2884
- #2894
- #2895
- #2897
=> it-IT: new strings 6646-6660

data/language/it-IT.txt
I just checked and fixed some strings that were either too wordy or not clear when seen in the game.
=> it-IT: small quality fixes

data/language/sv-SE.txt
- #2801
- #2720
- #2732
- #2755
- #2769
- #2794
- #2806
- #2814
- #2815
- #2821
- #2826
- #2836
- #2843
- #2854
- #2868
- #2869
- #2875
- #2881
- #2884
=> add new fields to sv-SE

data/language/hu-HU.txt
=> hu-HU: Apply #2894, #2895, #2897

data/language/ca-ES.txt
- #2894
- #2895
- #2897 
- #2909
=> ca-ES: Apply #2894, #2895, #2897, #2909

data/language/it-IT.txt
=> it-IT: apply #2909

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2909

data/language/hu-HU.txt
=> hu-HU: Apply #2909

data/language/de-DE.txt
- #2909
- #2895
- #2894
- #2897
=> de-DE: STR_6656 .. STR_6662

data/language/pt-BR.txt
=> pt-BR: Apply #2909

data/language/it-IT.txt
=> it-IT: apply #2917

data/language/pt-BR.txt
=> pt-BR: Apply #2917

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2917

data/language/es-ES.txt
=> es-ES: Apply #2894, #2895

data/language/hu-HU.txt
=> hu-HU: Apply #2917

data/language/es-ES.txt
=> es-ES: Apply #2917

data/language/pt-BR.txt
=> pt-BR: Apply #2928

data/language/eo-ZZ.txt
- #2928 
Plus small grammatical changes for STR_2488
=> eo-ZZ: Apply #2928

data/language/es-ES.txt
=> es-ES: Apply #2928

data/language/hu-HU.txt
=> hu-HU: Apply #2928

data/language/it-IT.txt
=> it-IT: #2928

data/language/pt-BR.txt
=> pt-BR: Apply #2936, #2938

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2936 #2938

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2941

data/language/pt-BR.txt
=> pt-BR: Apply #2941

data/language/eo-ZZ.txt
- #2945 
Plus typo fix for STR_6056
=> eo-ZZ: Apply #2945

data/language/pt-BR.txt
=> pt-BR: Apply #2945

data/language/hu-HU.txt
- #2936
- #2938
- #2941
- #2945
=> hu-HU: Apply #2936, #2938, #2941, #2945

data/language/hu-HU.txt
I'm very sorry, I didn't notice the new strings in #2945
=> hu-HU: missing strings from #2945

data/language/eo-ZZ.txt
Small fix for a typo I just noticed
=> eo-ZZ: Typo fix for STR_6697

data/language/es-ES.txt
- #2936 + consistency with older strings for "translucent"
- #2938
=> es-ES: Apply #2936, #2938

data/language/de-DE.txt
- #2917
- #2928
- #2936
- #2938
- #2941
- #2945
=> de-DE: Apply #2917, #2928, #2936, #2938, #2941, #2945

data/language/it-IT.txt
- #2936
- #2938
- #2941
- #2945
- #2960
=> it-IT: #2936, #2938, #2941, #2945, #2960

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2960

data/language/pt-BR.txt
=> pt-BR: Apply #2960

data/language/pl-PL.txt, objects/pl-PL.json
Another big overhaul, because I've found my old copy of the Triple Thrill Pack in Polish 😁
=> pl-PL: translate scenario names, improve existing translations

data/language/ca-ES.txt, objects/ca-ES.json
- #2917 
- #2928 
- #2936 
- #2938 
- #2941 
- #2945 
- #2960
=> ca-ES: Apply #2917, #2928, #2936, #2938, #2941, #2945, #2960

data/language/es-ES.txt
=> es-ES: Apply #2941

data/language/pl-PL.txt
=> pl-PL: Apply #2977

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2977

data/language/pt-BR.txt
=> pt-BR: Apply #2977

data/language/pl-PL.txt
=> pl-PL: Apply #2981

data/language/fr-FR.txt
- #2909
- #2917 
- #2928 
- #2936
- #2938
- #2941
- #2945 
- #2960
- #2977
- #2981
=> fr-FR: Update translations

data/language/ca-ES.txt, objects/ca-ES.json
=> ca-ES: Apply #2977 #2981

data/language/pl-PL.txt
=> pl-PL: Apply #2992

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #2992

data/language/pt-BR.txt
=> pt-BR: Apply #2992

objects/gl-ES.json
Translated the first lines of the gl-ES.json of objects to check if my work is correct, I hope to do it completely in a few weeks
=> gl-ES: Translate objects JSON

data/language/pt-BR.txt
=> pt-BR: Apply #2999

data/language/pl-PL.txt
=> pl-PL: Apply #2999

data/language/pt-BR.txt
=> pt-BR: Apply #3005

data/language/pt-BR.txt
=> pt-BR: Apply #3009

data/language/pt-BR.txt
=> pt-BR: Apply #3014

data/language/pl-PL.txt
=> pl-PL: Apply #3014

data/language/eo-ZZ.txt
- #2999 
- #3005 
- #3009 
- #3014 
- #3019 
Also made new translation of "peep" as "hometo" (little person)
=> eo-ZZ: Apply #2999 #3005 #3009 #3014 #3019

data/language/pt-BR.txt
=> pt-BR: Apply #3019, #3024

data/language/pl-PL.txt
=> pl-PL: Apply #3019, #3024

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3024

data/language/es-ES.txt
- #2960
- Updated LIM related strings: consistency + some parts were omitted 
- Consitent translation for "twist" related words: just a few used "retorcer" instead of "girar"
- Trim empty lines at the end of the file, sorry I left them in the prev PR
=> es-ES: Apply #2960

data/language/fr-FR.txt
- #2992
- #2999
- #3005
- #3009
- #3014
- #3019
- #3024
=> fr-FR: Apply #2992, #2999, #3005, #3009, #3014, #3019, #3024

data/language/pt-BR.txt
=> pt-BR: Apply #3035, #3037

data/language/gl-ES.txt, objects/gl-ES.json
gl_ES Applying for:
- #2999 
- #3005 
- #3009 
- #3014 
- #3019 
- #3021 
- #3024
=> update translation galician gl_ES

data/language/es-ES.txt
- #2977
- #2981
- Consistent translation for "rude"
- Consistent translation for "air time"
=> es-ES: Apply #2977, #2981

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3035 #3037

data/language/es-ES.txt
=> es-ES: Apply #2992

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3045

data/language/fr-FR.txt
=> fr-FR: Apply #3035, #3037, #3045

objects/ru-RU.json
=> ru-RU: Apply #3047

data/language/pt-BR.txt, objects/pt-BR.json
=> pt-BR: Apply #3047, #3045

objects/pl-PL.json
=> pl-PL: Apply #3047

data/language/pt-BR.txt
=> pt-BR: Apply #3056

data/language/pl-PL.txt
=> pl-PL: Apply #3056, #3060

data/language/da-DK.txt
=> Fix #3066: da-DK: Typo in scenario objective

data/language/ru-RU.txt
=> ru-RU: Apply #3069

data/language/ko-KR.txt
=> ko-KR: Apply #3069

data/language/pt-BR.txt
=> pt-BR: Apply #3069

data/language/pl-PL.txt
=> pl-PL: Apply #3069

data/language/fr-FR.txt
=> fr-FR: Apply #3056, #3060, #3069

data/language/eo-ZZ.txt
- #3056 
- #3060 
- #3069 
Plus a couple tiny grammar fixes
=> eo-ZZ: Apply #3056 #3060 #3069

data/language/gl-ES.txt, objects/gl-ES.json
- #3069
- #3076
- corrected line SRT 6728
=> Issues #3069 - #3076

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3082

data/language/de-DE.txt, objects/de-DE.json
Applying for issues #2960, #2977, #2981, #2999, #3005, #3009, #3014, #3019, #3024, #3035, #3037, #3045, #3047, #3047, #3056, #3060, #3069, #3076 and #3082.
=> de-DE: Apply #2960, #2977, #2981, #2999, #3005, #3009, #3014, #3019, #3024, #3035, #3037, #3045, #3047, #3047, #3056, #3060, #3069, #3076, #3082

data/language/pt-BR.txt
=> pt-BR: Apply #3082

data/language/en-US.txt
Localized a header in the cheats window. That should be everything for the US English localization for now.
=> en-US: Localized STR_6670 ("Guest behaviour")

data/language/fr-FR.txt
=> fr-FR: Apply #3076, #3082, #3094

data/language/fr-FR.txt
=> fr-FR: Apply #3100

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3100

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3094

data/language/pt-BR.txt
=> pt-BR: Apply #3100, #3094

data/language/fr-FR.txt
https://www.academie-francaise.fr/vous-faites-pour-vous-faites
=> Fix typo in fr-FR STR_0829

data/language/nl-NL.txt
- #3076
- #3082
- #3094 
- #3100 
- #3108
=> Updated Dutch translations

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3108 #3112

data/language/pt-BR.txt
=> pt-BR: Apply #3108, #3112

data/language/hu-HU.txt
- #2960
- #2977
- #2981
- #2992
- #2999
- #3005
- #3009
- #3014
- #3019
- #3024
- #3035
- #3037
=> hu-HU: Apply #2960, #2977, #2981, #2992, #2999, #3005, #3009, #3014, #3019, #3024, #3035, #3037

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3120

data/language/hu-HU.txt, objects/hu-HU.json
- #3045
- #3047
- #3056
- #3060
- #3069
- #3076
- #3082
- #3094
- #3100
- #3108
- #3112
- #3120
=> hu-HU: Apply #3045, #3047, #3056, #3060, #3069, #3076, #3082, #3094, #3100, #3108, #3112, #3120

data/language/hu-HU.txt
=> hu-HU: Apply #3124

data/language/pt-BR.txt
=> pt-BR: Apply #3124

data/language/fr-FR.txt
- #3108
- #3112 
- #3120 
- #3124
=> fr-FR: Apply #3108, #3112, #3120, #3124

data/language/pt-BR.txt
=> pt-BR: Apply #3130

data/language/hu-HU.txt
=> hu-HU: Apply #3130

data/language/gl-ES.txt
- #3094 (Strings 6752–6761)
- #3100 (String 6751)
- #3108 (Strings 5269, 6762)
- #3112 (String 6763–6765)
=> update galician translate

data/language/gl-ES.txt
=> galician update #3120 #3124 #3130

data/language/it-IT.txt
Oh boy, here we go... :laughing: 
- #2992
- #2981
- #2999
- #3005
- #3009
- #3014
- #3019
- #3024
- #3035
- #3037
- #3045
- #3056
- #3060
- #3069
- #3076
- #3082
- #3094
- #3100
- #3108
- #3112
- #3120
- #3124
- #3130
=> it-IT up to date

data/language/vi-VN.txt
=> vi-VN: Translate for vi-VN

objects/it-IT.json
=> it-IT apply #3047

data/language/it-IT.txt
=> it-IT apply #3144, #3147

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3144 #3147

data/language/cs-CZ.txt
fixed typos and grammar errors in strings 6493 to 6495
=> cs-CZ: fixed few typos and grammar errors

data/language/cs-CZ.txt
- #3112
- #3108
- #3100
- #3094
- #3082
- #3076
- #3069
- #3060 
- #3056
- #3045 
- #3037
- #3035
- #3024
- #3019
- #3014
- #3009
=> cs-CZ: Apply #3112 #3108 #3100 #3094 #3082 #3076 #3069 #3060 #3056 #3045 #3037 #3035 #3024 #3019 #3014 #3009

data/language/cs-CZ.txt
=> cs-CZ: Apply multiple issues

data/language/cs-CZ.txt
=> cs-CZ: Apply #2609

data/language/pt-BR.txt
=> pt-BR: Apply #3144, 3147

data/language/cs-CZ.txt
=> cs-CZ: Apply #2720

data/language/cs-CZ.txt
=> cs-CZ: Apply #2501

data/language/cs-CZ.txt
=> cs-CZ: Apply #2466

data/language/cs-CZ.txt
=> cs-CZ: Apply #2520

data/language/cs-CZ.txt
=> cs-CZ: Apply #2535

data/language/cs-CZ.txt
=> cs-CZ: Apply #2527

data/language/cs-CZ.txt
- #2550
STR_6541 needs no update, as #2960 is already applied to cs-CZ
=> cs-CZ: Apply #2550

data/language/cs-CZ.txt
=> cs-CZ: Apply #2551

data/language/cs-CZ.txt
=> cs-CZ: Apply #2562

data/language/cs-CZ.txt
=> cs-CZ: Apply #2563

data/language/cs-CZ.txt
=> cs-CZ: Apply #2578

data/language/cs-CZ.txt
=> cs-CZ: Apply #2594

data/language/cs-CZ.txt
=> cs-CZ: Apply #2602

data/language/cs-CZ.txt
=> cs-CZ: Apply #2620 & #2625 & #2631

data/language/cs-CZ.txt
Fix misc style, typos and grammar errors
=> cs-CZ: Fix misc

data/language/cs-CZ.txt
Fix mostly overall style to be unified with rest of translation
=> cs-CZ: Fix translations in Cheats window

data/language/cs-CZ.txt
Fix mostly minor typing errors and style
=> cs-CZ: Fix translations regarding visibility options

data/language/cs-CZ.txt, objects/cs-CZ.json
=> cs-CZ: Apply #2509

objects/cs-CZ.json
=> cs-CZ: Apply #2709

data/language/ca-ES.txt
- #3147 
- #3144 
- #3130 
- #3124 
- #3120 
- #3112 
- #3108 
- #3100 
- #3094
=> ca-ES: Apply #3147, #3144, #3130, #3124, #3120, #3112, #3108, #3100, #3094

data/language/cs-CZ.txt
- #3211
______
Note for reviewer: The word _gamepad_ requires no translation for cs-CZ
=> cs-CZ: Apply #3211

data/language/hu-HU.txt
=> hu-HU: Apply #3211

data/language/en-US.txt, data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3211

data/language/en-US.txt
Added American spelling for "Analog"
=> en-US: Localize STR_6787, STR_6789

data/language/de-DE.txt
=>  de-DE: Apply #3144, #3147, #3211 

data/language/fr-FR.txt, objects/fr-FR.json
- #3144
- #3147 
- #3211 
Also fixes a typo, makes a park name consistent, and improves an originally badly translated park name.
=> Update French translation

data/language/cs-CZ.txt
- Fix typos and colloquial forms of words (ran a spellcheck)
- Fix writing style of sentences in STR_0571 + -72, STR_0605
=> cs-CZ: Fix typos and style of sentences

data/language/sv-SE.txt
Applying for issue #3108
STR_6762 was already added in a previous commit
=> sv-SE: Apply #3108

data/language/da-DK.txt
=> da-DK: Apply #3108

data/language/sv-SE.txt
=> Update sv-SE for #2960

data/language/pt-BR.txt
=> pt-BR: Apply #3211

objects/sv-SE.json
- #3047
Note that "bill" was replaced with "skoter" for a more grammatically correct description.
=> Update objects sv-SE for #3047

data/language/pt-BR.txt
=> pt-BR: Apply #3244

data/language/es-ES.txt
- #3056
- #3060 
- #3069 
- #3076
Btw issues done in https://github.com/OpenRCT2/Localisation/pull/3229, don’t seem to have es-ES checkbox ticked.
Regards!
=> es-ES: Apply #3056, #3060, #3069, #3076

objects/es-ES.json
- #3047
- skidoo was not mentioned but no reference to snowmobiles either, so improved overall
- Improved consistency with few similar strings
- Translated few missing as mentioned in https://github.com/OpenRCT2/Localisation/pull/3231
=> es-ES: Apply #3047

data/language/hu-HU.txt
=> hu-HU: Apply #3244

data/language/ca-ES.txt
- #3094: seems like @J0anJosep missed these updated strings in his multi-issue PR
- https://github.com/OpenRCT2/Localisation/pull/3200
- Seems ok as I simply used the same titles as in strings STR_6752-STR_6754, but we can wait for him to confirm
Cheers
=> ca-ES: Apply #3094 (updated)

data/language/sv-SE.txt
=> sv-SE: Apply #3244

objects/cs-CZ.json
Remarks given in https://github.com/OpenRCT2/Localisation/pull/3260 apply here as well
=> cs-CZ: Add translation for RCT1AA scenario meta objects

data/language/pt-BR.txt, objects/pt-BR.json
- #3268
- Update taiwan park object entry
=> pt-BR: Apply #3268

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3244 #3268

data/language/pt-BR.txt
=> pt-BR: Apply #3277 

data/language/hu-HU.txt
=> hu-HU: Apply #3277

data/language/cs-CZ.txt
=> cs-CZ: Apply #3277

data/language/fr-FR.txt
=> fr-FR: Apply #3244, #3268, #3277

objects/cs-CZ.json
Shortened text to fit, fix wrong translation - no idea how this one slipped :|
=> cs-CZ: Minor fixes

data/language/cs-CZ.txt
=> cs-CZ: Apply #3289

data/language/pt-BR.txt
=> pt-BR: Apply #3289

data/language/hu-HU.txt
=> hu-HU: Apply #3289

data/language/eo-ZZ.txt
=> eo-ZZ: Apply #3289

data/language/cs-CZ.txt
=> cs-CZ: Apply #3317

data/language/es-ES.txt
- #3268
- #3277
- #3289
- #3328
> Btw the 8 issues done in https://github.com/OpenRCT2/Localisation/pull/3229, don’t seem to have es-ES checkbox ticked yet! thanks in advance
=> es-ES: Apply #3268, #3277, #3289, #3328

data/language/hu-HU.txt
=> hu-HU: Apply #3328

objects/eo-ZZ.json
Added the Esperanto translation for the Taiwan Park scenario in /objects
=> eo-ZZ: Added Taiwan Park translation

data/language/es-ES.txt, objects/es-ES.json
- #3317
- #3339
- Translated some strings related to audio that were next to it in the file
- Fixed "Hot and dry" translation
> Btw, regarding https://github.com/OpenRCT2/Localisation/issues/3314 for es-ES: there are no warnings and seems like nothing to suppress, so I would mark it as reviewed. I can comment there if you prefer!
=> es-ES: Apply #3317, #3339 + some missing in JSON

objects/fr-FR.json
=> fr-FR: Apply #3339

data/language/hu-HU.txt
=> hu-HU: Apply #3346

data/language/pt-BR.txt
=> pt-BR: Fix typo on STR_7003
