- data/language/english_uk.txt
- data/language/english_us.txt
These already are changed in the main repository.
> Add updated cheat strings

- data/language/dutch.txt
Reverts OpenRCT2/Localisation#5
> Revert "Add new Dutch cheat strings"

- data/language/dutch.txt
Hetzelfde als @ThomasDenH's commit #5, maar met juiste duizendtalscheiding.
> Add new Dutch cheat window strings, with fixed separator

- data/language/dutch.txt
- data/language/english_uk.txt
- data/language/english_us.txt
Ik heb voor deze vertaling gekozen omdat het me zo duidelijker lijkt.
> Add Dutch, UK English and US English string for (up) and (new file)

- data/language/french.txt
The first line difference is because I used Windows's Notepad to edit the file (I was at school), will be fixed in next PR.
> Second French translation update

- data/language/english_us.txt
> Add missing English (US) strings

- data/language/dutch.txt
- In het Nederlands is een hekje (#) voor een volgnummer niet correct.
- De instelling voor het muziek is veranderd van een keuzelijst (dropdown) in een selectievakje. Hierbij hoort geen dubbele punt. (Te zien in het venster met geluidinstellingen.)
A merge window of 24 hours is probably enough.
> Dutch interpunction

- data/language/dutch.txt
> Dutch: Differentiate between powered launch modes

- data/language/french.txt
Fixes include the date display and showing the difference between powered launch modes (see also issue #20).
> Some fixes and new translations for French

- data/language/dutch.txt
- data/language/english_us.txt
> Random title music

- data/language/dutch.txt
- data/language/english_us.txt
- data/language/french.txt
- data/language/german.txt
- data/language/hungarian.txt
- data/language/italian.txt
- data/language/polish.txt
- data/language/spanish_sp.txt
- data/language/swedish.txt
Merge after https://github.com/IntelOrca/OpenRCT2/pull/1085 has been merged.
> Update fast lift hill strings, add disable all breakdowns strings

- data/language/dutch.txt
- data/language/english_us.txt
Finally a string where the US English translation is actually different :)
> RCT1 colour scheme, closes #50

- data/language/german.txt
Discussed with @AllGoodNamesAreTaken.
> Merge https://github.com/IntelOrca/OpenRCT2/pull/704 into Localisation

- data/language/english_us.txt
> Fixed Case

- data/language/english_us.txt
- data/language/french.txt
- data/language/german.txt
- data/language/hungarian.txt
- data/language/italian.txt
- data/language/polish.txt
- data/language/spanish_sp.txt
- data/language/swedish.txt
> New strings added (options window)

- data/language/english_us.txt
- data/language/french.txt
- data/language/german.txt
- data/language/hungarian.txt
- data/language/italian.txt
- data/language/polish.txt
- data/language/spanish_sp.txt
- data/language/swedish.txt
> New strings (object search)

- data/language/german.txt
> DE: New cheats

- data/language/german.txt
> DE: New strings

- data/language/german.txt
> DE: New/updated strings

- data/language/dutch.txt
> NL: Fixes and new strings

- data/language/german.txt
> DE: Changed string

- data/language/chinese_traditional.txt
@Gymnasiast I think the issue should be fixed now :-P
> CHT: Translated some more strings, fixes #160

- data/language/german.txt
> DE: New strings (already merged ones)

- data/language/chinese_simplified.txt
start to work on simp. chinese translation
> simp. chinese #1

- data/language/chinese_traditional.txt
only ~80 strings to go. (excluding the credits for sure)
> CHT: Translated 160+ strings

- data/language/chinese_simplified.txt
> simp. chinese patch 2

- data/language/russian.txt
just first try of translation, so people can see it's not a joke)
> beginning of translation

- data/language/chinese_traditional.txt
> CHT: Synced strings from en-GB

- data/language/french.txt
Will continue translation later
> Partial update of french.txt

- data/language/korean.txt
> Translation complete

- data/language/finnish.txt
translated all of the rides, fixed some spelling/translation errors.
> Finnish.txt - translated & fixed ride names, spell checked.

- data/language/finnish.txt
also fixed some translations to sound more "natural"
> Translated various texts into finnish

- data/language/chinese_traditional.txt
This is just the beginning, and I will finish the translation slowly.
> CHT: Start translating Rides & Att.

- data/language/chinese_traditional.txt
and translated some attractions strings.
> CHT: New strings

- data/language/finnish.txt
Updated a bit and improved it a bit
> Updated translation

- data/language/german.txt
> DE: changed strings

- data/language/czech.txt
> Basic czech translation

- data/language/czech.txt
> CZ translation improvemnts

- data/language/portuguese_br.txt
more translated strings and some revised
> portuguese_br.txt

- data/language/japanese.txt
Chinese and Korean translations are up, but no Japanese! We can fix this.
> Created japanese file with some basic translations

- data/language/german.txt
> DE: New string

- data/language/portuguese_br.txt
As you said, I changed the strings 5525 to "Água escura" and 5526 to "Água clara"
> ptbr strings 5525/5526 changed

- data/language/german.txt
> DE: New/changed strings

- data/language/japanese.txt
Simple and (obviously) non-grammatically-involved strings
> JP: Translated a few strings

- data/language/korean.txt
Not fully translated, now on progress
> Translated some scenario/object names/desc.

- data/language/czech.txt
> CZE: small translation update

- data/language/portuguese_br.txt
added and translated strings: 5581, 5582, 5583, 5584, 5585, 5588
new empty strings: 5586, 5587
> added strings

- data/language/spanish_sp.txt
About 783-825: I think these are the ones used for dates, so I left them
in proper form. It should be "el {daynumber} de {month}" when formatted.
(either abbreviated or not)
I'm not very good at my Spanish, so this is just a first run through of
things I know for sure. More to come soon.
Also this might be more Latin/Mexican Spanish than Spanish Spanish, as the file name suggests. Might need a change there later.
> Some Spanish Translations

- data/language/japanese.txt
This adds a few more strings for the Japanese translation. Very much a work in progress still, but at least most of the HUD is translated now.
Translating the game is a challenge, even with intermediate proficiency, with all the technical terms. I'll ask around; maybe someone I know knows how to find appropriate translations for them.
> Work in progress: more strings for the Japanese translation

- data/language/korean.txt
* Translated RCT1 Scenario names/descriptions.
* Changed some terminologies.
* Applied #351
> Translated Scenarios of RCT1

- data/language/korean.txt
To display all texts correctly
> Insert new lines

- data/language/german.txt
> DE: updated string

- data/language/korean.txt
Applied #357, #359, #360 as @NeverDruid did in #365.
And translated more strings and fixed some typos.
> KR: #357, #359, #360 and more translations

- data/language/spanish_sp.txt
All the strings found on the "Options" window have been translated into spanish
> Translated the "Options" window

- data/language/portuguese_br.txt
Modified string 3324
Added 5633, 5634
Translated scenarios discriptions
> strings and translations

- data/language/czech.txt
I added some of the 5xxx Czech translations and also made a few very basic grammar corrections (spelling mistakes, capital letters, commas). I also replaced the Czech translation "host" of the word "guest" to "návštěvník", as it more accurately describes an amusement park visitor.
> CZE: New translations, grammar corrections

- data/language/spanish_sp.txt
Almost all of the strings in the main view are translated (date, guests, UI buttons, main windows, etc.)
> Translate more strings into spanish

- data/language/czech.txt
Large portion of strings translated - this time the editors, naming of foods/drinks (+thoughts, plurals, etc.) and some building mode strings
> CZE: Editor, food/drink and some building mode strings

- data/language/czech.txt
This should be the last batch of strings being translated to Czech. Right now, the only strings that are left untranslated are the names+descriptions of some of the rides/attractions - which are a real pain to translate/I'm not able to translate them accurately. Otherwise - after 3 days, everything else is now in Czech :-)
With 2k+ strings translated, it would be nice to be included in contributors file, it at all possible (don't know whether some special rules apply)
> CZE: (last) batch of strings translated

- data/language/czech.txt
I added all of .DAT strings to the czech.txt file (since RCT2 was never *officially* translated to Czech) and I translated the first ~2.5k section titled `RCT2 Objects` - that amounts to about a third of .DAT strings.
Oh boy oh boy, *so* many strings!
Sorry about *yet another* pull-request, but as @Killermannvs mentioned in pull request #380, a certain degree of cooperation between translators is required, when working in parallel.
> CZE: .DAT strings added & partially translated

- data/language/czech.txt
Another big chunk of translations coming right up, this time it's the Wacky Worlds expansion objects. Very annoying scenery titles! Somebody clearly had a strange passion for exact tree naming. Should all be translated now.
> CZE: .DAT Wacky Worlds object strings translated

- data/language/czech.txt
And here it is - the final batch of translations - all game scenarios. The game and all of it's content should now be translated into Czech. I'm sure I've overlooked some stuff, so some testing (by the Czech community?) will probably be required before calling this "fully translated", but the majority of work is now done. It took many, many hours. I'm so glad it's over :D
> CZE: .DAT Scenarios (RCT2 & WW & TT) strings translated

- data/language/czech.txt
Another big chunk of translations coming right up, this time it's the Time Twister expansion objects.  Should all be translated now. Getting closer and closer to 100% content translated, just scenarios left.
> CZE: .DAT Time Twister object strings translated

- data/language/japanese.txt
I found 暴走トロッコ on alc and it seems apt, so I went ahead and threw it in.
> JP: More progress

- data/language/czech.txt
Added & translated new strings, fix #390 ... damn, the Germans were faster this time :P
> CZE: Fix #390 - added & translated network game version strings

- data/language/czech.txt
CZE string changes associated with issue #393
> CZE: #393 - added & translated weather cheat strings

- data/language/korean.txt
Appled #405 and fixed STR_5502 and STR_5504
> KOR: Applied #405 and fixed some strings

- data/language/korean.txt
> KOR: #415, #416

- data/language/french.txt
FR: Translated some strings and corrected some typos.
> Some translations updated.

- data/language/chinese_simplified.txt
Some more translations and translation improvements in CHS
> CHS: some more translations

- data/language/korean.txt
* Apply #438
* Add {NEWLINE}'s to some tooltip texts
* Shorten Corkscrew Coaster's name
* Rename some special track's name
> KOR: Apply #438 and etc.

- data/language/spanish_sp.txt
100%, without scenary translations of RCT1.
> ES: Translations finished! (100%)

- data/language/portuguese_br.txt
> new strings

- data/language/portuguese_br.txt
new strings + translation improvements
> update ptbr + new strings

- data/language/swedish.txt
*Fixed spelling errors
*Filling in missed strings
*Added the new strings 
*Added myself as a maintainer in this document 
*Translated some new strings (50 %)
(*Not to be a douche - but corrected the spelling of "Maintainer" on the Note)
Overall progress: (75 %)
QUESTION: What is the difference between string 5649 & 5651?
> Update swedish + new strings 2016/03/14.txt

- data/language/portuguese_br.txt
> ptbr string changes

- data/language/english_us.txt
I noticed this wasn't updated already, so I'm PR'ing it now.
> en-US: Apply #438

- data/language/swedish.txt
Just the scenarios left, just wants to finish this to the next patch/stable version
Also, about STR 'All destructible'
#This needs to be changed, really confusing string + add a description (See issue #489 in Localisation on github)
> Swedish Translation - 70 % done

- data/language/swedish.txt
Every single string is translated, some small changes are made to fit inside the layout of the game, spelling corrections
Todo; Check in the newest version for errors and correct spelling mistakes if found
> Updated Swedish.txt - 95-100% translated (2016-03-30)

- data/language/swedish.txt
> SWE- 99% translated 2016-03-31

- data/language/korean.txt
Fixed a typo and modified a wrong-translated string.
> KOR : Fixed a typo and so on

- data/language/french.txt
> FR: Strings from #506 translated

- data/language/swedish.txt
> SE - Added strings 5790 -> 5797

- data/language/spanish_sp.txt
PS: I have improved some translations (STR_5157 and STR_5368).
> ES: Apply #506

- data/language/chinese_traditional.txt
STR_5127 should be improved somewhere in the future.
> CHT: #511, #506, #514

- data/language/swedish.txt
Added the new string STR_5665 - #523 
Changed string STR_1058 (Text was out of border in-game)
> SE: Added STR_5665

- data/language/japanese.txt
This resolves the discussion in #482, giving credit to the original translators.
> Japanese translation update

- data/language/french.txt
Improvements to consistency, string length and other grammatical corrections.
> FR: Corrections & improvements

- data/language/french.txt
Corrections in marketing campaigns and Bumbly Beach translation
> FR: Corrections

- data/language/chinese_simplified.txt
CHS: update Simplified Chinese translation
> CHS: update Simplified Chinese translation

- data/language/swedish.txt
Translated it all, proof-read it and spell checked it with Libre office proof-reading software
Added the string from #535
> SE: 100% translated + Added str from #535

- data/language/swedish.txt
> SE: Apply #545 #548 #551

- data/language/korean.txt
song name should not be translated(at least it should be translated whole, not 블록buster)
Note to myself: use `[ci skip]` next time
> Fix wrong translation

- data/language/italian.txt
I've translated some strings and fixed some typos.
> New strings translated

- data/language/swedish.txt
> SE: Apply #567

- data/language/portuguese_br.txt
new strings and translation updates
> new strings and translation updates

- data/language/italian.txt
New strings added
Base game scenario descriptions extracted from vanilla exe
> IT: new strings added, new translations

- data/language/ko-KR.txt
Translated...
* All object's names
* Some ride's descriptions
> KOR: Translated more

- data/language/sv-SE.txt
> sv-SE apply #582

- data/language/sv-SE.txt
> sv-SE: Apply #590 #593

- data/language/sv-SE.txt
> sv-SE: Apply #600 

- data/language/ko-KR.txt
> KOR: Apply #600, totally translated

- data/language/pt-BR.txt
added and translated new strings
> added new strings

- data/language/es-ES.txt
And another mistake translated.
> es-ES: Apply #600

- data/language/fr-FR.txt
Minor orthographic corrections along with better consistency with the original game translation
> FR - Corrections

- data/language/it-IT.txt
I hope to continue with the translations in the next days :-)
> few italian translations

- data/language/sv-SE.txt
> Apply #611

- data/language/cs-CZ.txt
Removing STR_5813/5814, not sure what those are doing there, since they are covered by #625.
> cs-CZ: Apply #625

- data/language/fr-FR.txt
Apply #625 plus consistency corrections
> FR: Apply #625

- data/language/ja-JP.txt
I adjusted some existing translations to match some entries on the wiki that was posted a while back and added a few new ones. I'll try to get working on descriptions and a bunch of the important stuff that's not translated yet.
> JP: Some updates to match existing translations

- data/language/en-US.txt
> Apply #625

- data/language/sv-SE.txt
*Applies: #645  #632  #625 
*Changes the music's names (More off a test)
*Fixes many text strings that are out of the bounderies
> sv-SE: Apply all issues + other changes

- data/language/cs-CZ.txt
- data/language/de-DE.txt
- data/language/en-US.txt
- data/language/es-ES.txt
- data/language/fi-FI.txt
- data/language/fr-FR.txt
- data/language/it-IT.txt
- data/language/ja-JP.txt
- data/language/ko-KR.txt
- data/language/nl-NL.txt
- data/language/pl-PL.txt
- data/language/pt-BR.txt
- data/language/sv-SE.txt
- data/language/zh-CN.txt
- data/language/zh-TW.txt
> Apply #670 for all languages

- data/language/sv-SE.txt
> SE: Apply #674

- data/language/fr-FR.txt
Apply #674 + minor corrections
> FR: Apply 674

- data/language/fi-FI.txt
It's just one string in the masses, as Finnish is almost 100% translated (but missing new strings), I don't think it would be fair to remove it as it seems like it's something that could easily be missed then.
#645
> fi-FI: Apply #645

- data/language/cs-CZ.txt
Guess it should have been said before it got merged, if it matters :o
> Moving STR_5666

- data/language/nb-NO.txt
`STR_0000` through `STR_0556` have been translated. Additions and revisions to come.
> Added initial translation for Norwegian Bokmål.

- data/language/es-ES.txt
> es-ES: Apply #693 & #698

- data/language/sv-SE.txt
_If you're applying strings from an issue, please fill it out bellow_
- Applying for issue: #693 
- Applying for issue: #698
_Additional information/other:_
Changed a rides name
> sv-SE: Apply #693 and #698

- data/language/nb-NO.txt
Translation of:
STR_0562 - STR_0567,
STR_0602 - STR_0991
Some rewording and halfway-translations.
> Additional nb-NO translations

- data/language/pt-BR.txt
new strings, fixed strings and translation
> ptbr new strings, fixed strings and translation

- data/language/it-IT.txt
> IT: Fix #674, #693, #698

- data/language/ja-JP.txt
- data/language/pl-PL.txt
[#645](https://github.com/OpenRCT2/Localisation/issues/645)
> Remove STR_3160 from PL + JP

- data/language/it-IT.txt
Updated some strings in the Italian translation
> it-IT: Updated strings

- data/language/nb-NO.txt
Minor fix, more translations
Apply #693, #698
> Additional translation for nb-NO. Apply #693, #698

- data/language/sv-SE.txt
> Apply #716

- data/language/de-DE.txt
Added STR_5666, STR_5861 - STR_5870
> de-DE: Apply #674, #693, #698

- data/language/es-ES.txt
> es-ES: Apply #716

- data/language/es-ES.txt
> es-ES: Apply #632

- data/language/es-ES.txt
> es-ES: Apply #723

- data/language/sv-SE.txt
> Apply #723

- data/language/fr-FR.txt
> FR: Apply #716 & #723

- data/language/sv-SE.txt
> Apply #730

- data/language/es-ES.txt
> es-ES: Apply #730

- data/language/fr-FR.txt
> FR: Apply #730

- data/language/zh-TW.txt
5873,74&78 may require polish later on.
> zh-TW: #716, #723, #730, AA/LL Scenario part 3

- data/language/nb-NO.txt
> nb-NO: Apply #716 #723 #730

- data/language/it-IT.txt
Fixed a lot of translation errors. Added some missing strings
> it-IT: Fixed translation errors, added strings

- data/language/it-IT.txt
Removed double exclamation marks ("!!"), other small fixes.
> it-IT small fixes

- data/language/fr-FR.txt
> FR: Apply #749

- data/language/it-IT.txt
> it-IT: apply #761

- data/language/sv-SE.txt
> Apply #761

- data/language/fr-FR.txt
> FR: Apply #761

- data/language/es-ES.txt
> es-ES: Apply #761

- data/language/sv-SE.txt
> Apply #771

- data/language/es-ES.txt
> es-ES: Apply #786

- data/language/fr-FR.txt
> FR: Apply #771 & #786

- data/language/it-IT.txt
> it-IT: apply #786

- data/language/fr-FR.txt
> FR: Apply #797

- data/language/es-ES.txt
> es-ES: Apply #797

- data/language/nb-NO.txt
#786 #797 
Note to potential Norwegian translators in the future: I am unsure about the translation of "track" to "bane". Would be nice to have a discussion.
> nb-NO: Apply #786 #797

- data/language/nl-NL.txt
> nl-NL: Apply #797 and #806

- data/language/cs-CZ.txt
> cs-CZ: Apply #816

- data/language/sv-SE.txt
> sv-SE: Apply #786, #797, and #806

- data/language/es-ES.txt
> es-ES: Apply #806, #816

- data/language/de-DE.txt
> de-DE: Apply #806 & #816

- data/language/fr-FR.txt
> FR: Apply #806 & #816

- data/language/nl-NL.txt
> nl-NL: Apply #816

- data/language/fr-FR.txt
> FR: Apply #829

- data/language/de-DE.txt
> de-DE: Apply #829 & improvements

- data/language/nl-NL.txt
> nl-NL: Apply 829

- data/language/es-ES.txt
> es-ES: Apply #829

- data/language/nl-NL.txt
> nl-NL: Apply #840

- data/language/es-ES.txt
> es-ES: Apply #840

- data/language/fr-FR.txt
> FR: Apply #840

- data/language/nl-NL.txt
Niet zeker over het weglaten van een vertaling van "custom", maar dat is sowieso een lastig woord om naar het Nederlands te vertalen en voegt volgens mij in deze context weinig toe.
#848
> nl-NL: Apply #848

- data/language/fr-FR.txt
Apply #848, #851 + minor corrections
> FR: Apply #848, #851 + corrections

- data/language/es-ES.txt
> es-ES: Apply #848 #851 #859

- data/language/sv-SE.txt
> sv-SE: Apply #829, #840, #848, #851

- data/language/fr-FR.txt
> FR: Apply #859

- data/language/de-DE.txt
> de-DE: Apply #840, #848, #851 & #859

- data/language/nb-NO.txt
#806 #816 #829 #840 #848 #851 #859 
Sorry for the late updates, I should be back to procrastinating from schoolwork in two weeks time!
> Apply #806 #816 #829 #840 #848 #851 #859

- data/language/sv-SE.txt
> Apply #859

- data/language/fr-FR.txt
> FR: Apply #871

- data/language/it-IT.txt
> it-IT: apply #871

- data/language/cs-CZ.txt
> cs-CZ: Apply #876

- data/language/fr-FR.txt
> FR: Apply #876

- data/language/sv-SE.txt
> sv-SE: Apply #871 & #876

- data/language/it-IT.txt
> it-IT: apply #876

- data/language/nb-NO.txt
> nb-NO: Apply #871 #876

- data/language/cs-CZ.txt
> cs-CZ: Apply #893

- data/language/fr-FR.txt
> FR: Apply #893

- data/language/it-IT.txt
> it-IT: apply #893

- data/language/sv-SE.txt
> sv-SE: Apply #903 #901 #893

- data/language/nb-NO.txt
As swedish and Norwegian are similar
> NB-no - Apply #893

- data/language/fr-FR.txt
> FR: Apply #901 & #903

- data/language/es-ES.txt
> es-ES: Apply #913

- data/language/cs-CZ.txt
- Applying for issue: #913 
cs-CZ: Apply #913
> cs-CZ: Apply #913

- data/language/it-IT.txt
> it-IT: apply #913

- data/language/fr-FR.txt
> FR: Apply #913

- data/language/fr-FR.txt
> FR: Apply #925

- data/language/ko-KR.txt
> ko-KR: Apply #925

- data/language/cs-CZ.txt
> cs-CZ: Apply #925

- data/language/de-DE.txt
- Applying for issue: #901, #903, #913 & #925
> de-DE: Apply #901, #903, #913 & #925

- data/language/es-ES.txt
> es-ES: Apply #925

- data/language/it-IT.txt
> it-IT: apply #925 and new translations

- data/language/ko-KR.txt
> ko-KR: Apply #931

- data/language/cs-CZ.txt
> cs-CZ: Apply #931

- data/language/de-DE.txt
> de-DE: Apply #931

- data/language/zh-TW.txt
- Applying for issue: #913, #925, #931 & #935
Long overdue update. Please note that #913 is still not finished yet, due to my limited understanding of tile inspector.
> zh-TW: #913, #925, #931 & #935

- data/language/es-ES.txt
> es-ES: Apply #931, #935

- data/language/zh-CN.txt
- Applying for issue: #901 #903 #913 #925 #931 #935
> zh-CN: Apply #901 #903 #913 #925 #931 #935

- data/language/it-IT.txt
Apply #931 and #935 + other translations
> it-IT: apply #931 and #935 + other translations

- data/language/zh-TW.txt
As being mentioned here #949, it does indeed seem like the tests failed from a specific PR and the log shows which lines which should have been corrected to the right spacing symbol being used
> Fix #949 - CI failure in localisation

- data/language/sv-SE.txt
- Applying for issue: #931 & #925
- Minor changes (Better wording/size limitation)
> sv-SE: Apply #931, #925 & Minor changes 

- data/language/nb-NO.txt
> nb-NO: Apply #935

- data/language/ko-KR.txt
> ko-KR: Minor updates

- data/language/zh-CN.txt
> zh-CN: Apply #956

- data/language/de-DE.txt
> de-DE: Apply #956

- data/language/es-ES.txt
> es-ES: Apply #956

- data/language/de-DE.txt
> de-DE: Apply #963

- data/language/ko-KR.txt
> ko-KR: Apply #963 and misc.

- data/language/es-ES.txt
> es-ES: Apply #963

- data/language/sv-SE.txt
- Applying for issue: #931, #956, #963
> SE-sv: Apply 931, 956, 963

- data/language/it-IT.txt
> it-IT: apply #956 and #963

- data/language/zh-CN.txt
> zh-CN: Apply #963

- data/language/zh-TW.txt
> zh-TW: #963, AA Scenario part 4

- data/language/sv-SE.txt
> sv-SE apply 975

- data/language/es-ES.txt
> es-ES: Apply #974, #975

- data/language/ko-KR.txt
> ko-KR: Apply #975

- README.md
Now when we[ can log changes to the languages,](https://github.com/OpenRCT2/Localisation/commit/f5d1f08b72d235d2b8eb31f404afb1f1e0d2e74c) this layout and re-work could be brought up for suggestions, thoughts and discussions :smile: 
Changing the layout and the file mostly for getting more information easier out to the people when;
**Pros:**
*Better language status
*Public maintainers name for contact
*Good for new translators
*Information on how to maintain a language
Inspired by https://translation.steampowered.com/
> Rework for Readme - Live language status 

- data/language/cs-CZ.txt
- data/language/de-DE.txt
- data/language/fr-FR.txt
- data/language/it-IT.txt
- data/language/nb-NO.txt
- data/language/nl-NL.txt
- data/language/pt-BR.txt
- data/language/zh-CN.txt
- data/language/zh-TW.txt
Applying for issue: #975
There is being a lot off open issues, closing some would make it easier
**the first line gets a edited for some reason, does it make any difference?**
> Apply 975 to all maintained languages

- data/language/zh-TW.txt
- Applying for issue: #974 
Happy Lunar New Year guys :)
> zh-TW: #974

- data/language/de-DE.txt
> de-DE: Apply #974

- data/language/cs-CZ.txt
-  #663
-  #956
-  #963
-  #974
> cs-CZ: Apply a batch of issues

- data/language/nb-NO.txt
- Applying for issue: #663, #901, #903, #913, #925, #931, #956, #963, #974
> nb-NO: Catchup

- data/language/zh-CN.txt
> zh-CN: Apply #663

- data/language/ko-KR.txt
* Fix a grammar.
* Fix a mistranslated string.
> ko-KR: Fix minor things

- data/language/ko-KR.txt
> ko-KR: Apply #990

- data/language/cs-CZ.txt
> cs-CZ: Apply #990

- data/language/ca-ES.txt
I would like to add the Catalan translation of the game.
Thank you.
> Add the Catalan translation for OpenRCT2.

- data/language/pl-PL.txt
> Remove untranslated strings from pl-PL.txt

- data/language/nb-NO.txt
- Applying for issue: #990 #995
> nb-NO: Apply #990 #995

- data/language/zh-TW.txt
A little bit rushed and needed polish, and I am uncertain about STR_6015.
- Applying for issue: #990 , #995
> zh-TW: #990, #995

- data/language/cs-CZ.txt
> cs-CZ: Apply #995

- data/language/zh-CN.txt
- Applying for issue: #990 #995
> zh-CN: Apply #990 #995

- data/language/zh-CN.txt
fix some improper translations
> zh-CN: fix translation

- data/language/fr-FR.txt
> fr-FR: Apply #931

- data/language/fr-FR.txt
- Applying for issue: #956 #963 #974 #990 #995
> fr-FR: Apply #956 #963 #974 #990 #995

- data/language/sv-SE.txt
> sv-SE: Apply 995

- data/language/sv-SE.txt
- Applying for issue: # 974, 990
> sv-SE: Apply 974, 990

- data/language/fr-FR.txt
> fr-FR: Apply #1015

- data/language/cs-CZ.txt
> cs-CZ: Apply #1015

- README.md
Just some slight maintenance as a new language were added
Note; "Checking & testing strings in-game" could be written differently and better
> Readme: Add new topic, add new language ca-ES and move up nb-NO to maintained

- data/language/zh-CN.txt
> zh-CN: Apply #1015

- data/language/fr-FR.txt
> fr-FR: Apply #1021

- data/language/ca-ES.txt
- Applying for issue: #995 #1015 #1021
> ca-ES: Amend some strings. Apply #995 #1015 #1021.

- data/language/cs-CZ.txt
> cs-CZ: Apply #1021

- data/language/es-ES.txt
> es-ES: Apply #990 #995 #1015 #1021

- data/language/sv-SE.txt
- Applying for issue: 
#1015 
#1021
> sv-SE: Apply 1021+1015

- data/language/it-IT.txt
- Applying for issues #974, #990, #995, #1015
- Fixed minor issues and new strings from STR_6018 through STR_6029
> Updated it-IT

- data/language/nb-NO.txt
- Applying for issue: #1015 #1021 #1034 
... and translations for RCT Original scenario descriptions
> nb-NO: Apply #1015 #1021 #1034

- .github/PULL_REQUEST_TEMPLATE
The current PR template has a slight grammar issue ("a issue"), this slightly rewords the template and fixes the grammatical error.
> Slight rewording of pull request template

- README.md
The status bars are stuck at 0% - this PR doesn't fix that
but the bars are also in a cluster, the formating has been corrected and the invisible comment between the bars have been removed to restore their shape
> Format & status fix (broken)

- data/language/de-DE.txt
> de-DE: Translated Strings 6013-6014, fixes #990

- data/language/cs-CZ.txt
- Applying for issue: #1044 
- Applying for issue: #1034
> cs-CZ: Apply #1044

- data/language/sv-SE.txt
- Applying for issue: #1034 #1044
> sv-SE: Applying #1034 & #1044

- data/language/sv-SE.txt
> sv-SE: Insert missing strings to make langcheck 100%

- data/language/ko-KR.txt
> ko-KR: Apply #1053

- data/language/fr-FR.txt
- Applying for issue: #1034 #1044 #1053
> [fr-FR] Apply #1034 #1044 #1053

- data/language/es-ES.txt
- Applying for issue: #1034, #1044, #1053
> es-Es: Apply #1034, #1044, #1053

- data/language/es-ES.txt
> Update es-ES.txt String 6039 - 6041

- data/language/es-ES.txt
https://github.com/OpenRCT2/Localisation/pull/1058#issuecomment-294412989
> es-ES: Fix some mistranslations

- data/language/ko-KR.txt
> ko-KR: Apply #1057

- data/language/sv-SE.txt
> sv-SE: apply 1057

- data/language/zh-CN.txt
- Applying for issue: #1034 #1044 #1053 #1057
> zh-CN: Apply #1034 #1044 #1053 #1057

- data/language/zh-TW.txt
- Applying for issue: #1053, #1057
> zh-TW: #1053, #1057

- data/language/nb-NO.txt
- Applying for issues: #1044 #1053 #1057
And more base translation. Only a couple of thousand strings to go... :)
> nb-NO: Catch-up 2017-04-21

- data/language/nb-NO.txt
> nb-NO: Apply #1068

- data/language/de-DE.txt
- #995
- #1015
- #1021
- #1034
- #1044
- #1053
- #1057
> de-DE Apply #995, #1015, #1021, #1034, #1044, #1053, #1057

- data/language/de-DE.txt
> de-DE Apply #663

- data/language/ca-ES.txt
- #1034
- #1044
- #1053
- #1057
- #1068
- #1072
- #1078
> ca-ES: Apply #1034 #1044 #1053 #1057 #1068 #1072 #1078

- data/language/it-IT.txt
Apply:
- #1034 
- #1044
- #1053 
- #1057
- #1068
- #1072
- #1078
> New it-IT translations

- data/language/ko-KR.txt
> ko-KR: Translate an untranslated string

- data/language/nb-NO.txt
> nb-NO: Apply #1072 and mapgen strings

- data/language/it-IT.txt
> it-IT: apply #1086

- data/language/cs-CZ.txt
A big cs-CZ translation package. Sorry about the delay.
- #1053
- #1057
- #1068
- #1072
- #1078
- #1086
> cs-CZ: batch translation

- data/language/it-IT.txt
Enhanced translations after in-game proofreading.
Also, removed strange UTF-8 character at the beginning of the file.
> it-IT: better translations

- data/language/sv-SE.txt
- #1086
- #1078
- #1072
- #1068
- #1053
> sv-SE: catching up

- data/language/zh-TW.txt
> zh-TW: AA & LL Scenario part finale

- data/language/es-ES.txt
> es-ES: Apply 1068

- data/language/fr-FR.txt
> fr-FR: Apply 1068

- data/language/de-DE.txt
> de-DE: Apply 1068

- data/language/nb-NO.txt
> nb-NO: #1078 #1086

- data/language/ko-KR.txt
> ko-KR: Fix a mistranslation

- data/language/ko-KR.txt
> ko-KR: Apply #1105 and STR_6059

- data/language/zh-CN.txt
> zh-CN: more translations

- data/language/es-ES.txt
> es-ES: Apply #1078, #1086, #1105, #1108

- data/language/fr-FR.txt
- #1072 
- #1078 
- #1086 
- #1105 
- #1108
> fr-FR: Apply #1072 #1078 #1086 #1105 #1108

- data/language/ko-KR.txt
> ko-KR: Apply #1108, #1111

- data/language/it-IT.txt
> it-IT: apply #1105, #1108, #1111 and other enhancements

- data/language/it-IT.txt
> it-IT: apply #1114 and old missing strings

- data/language/it-IT.txt
> it-IT: apply #1117

- data/language/cs-CZ.txt
- #1105
- #1108
- #1111
- #1114
- #1117
> cs-CZ: a bunch of translations

- data/language/cs-CZ.txt
> cs-CZ: Apply #1122

- data/language/de-DE.txt
> de-DE: Apply #1086 and #1105

- data/language/de-DE.txt
- #1108
- #1111
- #1114
- #1117
- #1122
> de-DE: New strings

- data/language/cs-CZ.txt
> cs-CZ: Apply #1129

- data/language/it-IT.txt
> it-IT: apply #1122 #1129

- data/language/cs-CZ.txt
> cs-CZ: Apply #1133

- data/language/de-DE.txt
> de-DE: #1129 and #1133

- data/language/it-IT.txt
> it-IT: apply #1133

- data/language/sv-SE.txt
- #1105
- #1108
- #1111
- #1114
- #1117
- #1122 _(covered in 1117)_
- #1129
- #1133
- #1138
For commit f9b58ff see [#5690](https://github.com/OpenRCT2/OpenRCT2/issues/5690)
> sv-SE: Apply issues & corrections

- data/language/cs-CZ.txt
> cs-CZ: Apply #1138

- data/language/zh-TW.txt
Fix #1105, #1111, #1114, #1129, #1133, #1138
Partially fix #1108, #1117
> zh-TW: Cumulative update, part 1

- data/language/ca-ES.txt
- data/language/cs-CZ.txt
- data/language/de-DE.txt
- data/language/es-ES.txt
- data/language/fi-FI.txt
- data/language/fr-FR.txt
- data/language/it-IT.txt
- data/language/ja-JP.txt
- data/language/ko-KR.txt
- data/language/nb-NO.txt
- data/language/nl-NL.txt
- data/language/pt-BR.txt
- data/language/sv-SE.txt
- data/language/zh-CN.txt
- data/language/zh-TW.txt
[ci-skip]
Applying for pull request:
http://github.com/OpenRCT2/OpenRCT2/issues/5755
> Uint for title editor

- data/language/sv-SE.txt
> sv-SE: Apply #1146

- data/language/cs-CZ.txt
> cs-CZ: Apply #1146

- data/language/it-IT.txt
> it-IT: apply #1138 and #1146

- data/language/zh-CN.txt
- #1105 
- #1108 
- #1111 
- #1114 
- #1117 
- #1122 
- #1129 
- #1133 
- #1138 
- #1146
> zh-CN: Apply #1105 #1108 #1111 #1114 #1117 #1122 #1129 #1133 #1138 #1146

- data/language/es-ES.txt
- #1111 
- #1114 
- #1117 
- #1122 
- #1129 
- #1133 
- #1138 
- #1146
> es-ES: Apply #1111 #1114 #1117 #1122 #1129 #1133 #1138 #1146

- data/language/de-DE.txt
> de-DE: Apply #1138 and #1146

- data/language/zh-TW.txt
> zh-TW: cumulative update, part 2

- data/language/sv-SE.txt
> sv-SE: Apply 1162

- data/language/cs-CZ.txt
> cs-CZ: Apply #1162

- data/language/ca-ES.txt
- #1086
- #1105
- #1108
- #1111
- #1114
- #1117
- #1122
- #1129
- #1133
- #1138
- #1146
- #1162
> ca-ES: Apply #1086 #1105 #1108 #1111 #1114 #1117 #1122 #1129 #1133 #1138 #1146 #1162

- data/language/sv-SE.txt
> Sv-SE: Apply #1168

- data/language/zh-CN.txt
> zh-CN: Apply #1168

- data/language/cs-CZ.txt
> cs-CZ: Apply #1168

- data/language/cs-CZ.txt
> cs-CZ: Apply #1174

- data/language/nb-NO.txt
- #1105 
- #1108 
- #1111 
- #1114 
- #1117 
- #1129 
- #1133 
- #1138 
- #1146 
- #1162 
- #1168 
- #1174 
... and a minor change.
> nb-NO: Catch-up 2017-07-30

- data/language/fr-FR.txt
- #1111 
- #1114 
- #1117 
- #1122 
- #1133 
- #1138 
- #1146 
- #1162
- #1174
> fr-FR: Apply #1111 #1114 #1117 #1122 #1129 #1133 #1138 #1146 #1162 #1174

- data/language/de-DE.txt
> de-DE: Apply #1162, #1168 and #1174

- data/language/sv-SE.txt
> sv-SE: Apply #1174

- data/language/nb-NO.txt
> nb-NO: Apply #1182

- data/language/cs-CZ.txt
> cs-CZ: Apply #1182

- data/language/de-DE.txt
> de-DE: Apply #1182

- data/language/sv-SE.txt
> sv-SE: Apply #1182

- data/language/de-DE.txt
> de-DE: Apply #1188

- data/language/ko-KR.txt
> ko-KR: Apply #1188

- data/language/cs-CZ.txt
> cs-CZ: Apply #1188

- data/language/zh-TW.txt
#1162, #1168, #1174, #1182, #1188
> zh-TW: #1162, #1168, #1174, #1182, #1188

- data/language/sv-SE.txt
> sv-SE: Apply 1188

- data/language/zh-CN.txt
> zh-CN: Apply #1174 #1182 #1188

- data/language/it-IT.txt
it-IT apply issues and more fixes, including an original wrong translation for Ivory Towers description.
- #1162 
- #1168 
- #1174 
- #1182 
- #1188
> it-IT apply #1162, #1168, #1174, #1182, #1188 and more fixes

- data/language/ko-KR.txt
> ko-KR: Apply #1197

- data/language/zh-CN.txt
> zh-CN: Apply #1197

- data/language/sv-SE.txt
> sv-SE: apply #1197

- data/language/cs-CZ.txt
> cs-CZ: Apply #1197

- data/language/sv-SE.txt
> sv-SE: apply #1206

- data/language/de-DE.txt
> de-DE: Apply #1197

- data/language/cs-CZ.txt
> cs-CZ: Apply #1206

- data/language/ar-EG.txt
> arabic agian sorry

- data/language/ar-EG.txt
https://ci.appveyor.com/project/IntelOrca/localisation/build/1.0.1700#L22
> ar-EG: Fix AppVeyor build

- data/language/de-DE.txt
> de-DE: Apply #1206

- .github/ISSUE_TEMPLATE.md
Suggestion brought up on [Gitter](https://gitter.im/OpenRCT2/Localisation?at=59b6c902614889d475e582bb)
Makes the process more automatic with minimal resources like a bot - Good for people who want to get a notification when new strings arrive but not get a notification on all updates in the respitory
> Issue_template - Add notification-section

- data/language/de-DE.txt
> de-DE: Apply #1217

- data/language/cs-CZ.txt
> cs-CZ: Apply #1217

- .github/ISSUE_TEMPLATE.md
- README.md
- data/language/en-US.txt
Localisation: Add user for notification
_Goddsen is someone who have talked about it_
Localisation: Add ar-EG to readme
_As the language seems to move along (also moved en-us further down as it's a bit special)_
Localisation - Minor edits
_Custom message to further mark how the language is used_
> Localisation: Minor changes

- data/language/ar-EG.txt
> Arabic EG Update (big one)

- data/language/pl-PL.txt
@janisozaur Could you check if you see any odd characters? It doesn't seem to use any known codepage, so I manually converted the characters.
> pl-PL: Add .DAT translations

- data/language/sv-SE.txt
> sv-SE: apply #1217

- data/language/es-ES.txt
- #1162
- #1168
- #1174
- #1182
- #1188
- #1197
- #1206
- #1217
> es-ES: Apply #1162 #1168 #1174 #1182 #1188 #1197 #1206 #1217

- data/language/zh-CN.txt
> zh-CN: Apply #1217

- data/language/ar-EG.txt
> Arabic update #1

- data/language/it-IT.txt
> updated IT translation

- data/language/it-IT.txt
> it-IT proofreading #1233

- data/language/fr-FR.txt
- #1182 
- #1188 
- #1197 
- #1206 
- #1217
> fr-FR: Apply #1182 #1188 #1197 #1206 #1217

- data/language/ca-ES.txt
- #1174 
- #1182
- #1188
- #1197
- #1206
- #1217
- #1168
> es-CA: Apply #1174 #1182 #1188 #1197 #1206 #1217 #1168

- data/language/ca-ES.txt
> ca-ES: Fix for issues #1188 and #1168

- data/language/ja-JP.txt
Little by little, the Japanese translation is getting more and more complete. :)
> ja-JP: another batch of translations

- data/language/zh-TW.txt
Also fix the procrastination of the translator aka me.
#1197, #1206, #1217
> zh-TW: #1197, #1206, #1217

- data/language/cs-CZ.txt
> cs-CZ: Apply #1245

- data/language/sv-SE.txt
> sv-SE: Apply #1245

- data/language/nb-NO.txt
- #1188
- #1197
- #1206
- #1217
- #1245
> nb-NO_catchup_2017-10-11

- data/language/it-IT.txt
> it-IT: apply #1245

- data/language/ar-EG.txt
i will be offline for about 1 month for my final exam 
so this is last update until then
> Arabic Update

- data/language/sv-SE.txt
> sv-SE: Apply #1257

- data/language/ja-JP.txt
With #1254 on its way, I figured I'd throw in the as-of-yet uncommitted changes I had locally as well. I believe these shouldn't conflict with the other PR, but if they do, I'll happily amend my PR after the other is merged.
> ja-JP: various ride-related updates.

- data/language/ja-JP.txt
Various ride related translations, as well as some more of the guests' thoughts. Very nice seeing more and more of the interface turning Japanese, haha.
This PR also incorporates #1254, addressing the feedback in that PR.
> ja-JP: another update

- data/language/sv-SE.txt
> sv-SE: apply #1259

- data/language/cs-CZ.txt
> cs-CZ: Apply #1257 #1259

- data/language/ja-JP.txt
Getting to a point where most of the game's regular interface is translated, save for tooltips, scenery, and other details.
> ja-JP: various translations

- data/language/nb-NO.txt
> nb-NO: Apply #1257 #1259

- data/language/de-DE.txt
> de-DE translation for #1245

- data/language/cs-CZ.txt
> cs-CZ: Apply #1269

- data/language/sv-SE.txt
> sv-SE: Apply #1269

- data/language/it-IT.txt
> it-IT: apply #1257, #1259, #1269

- data/language/ja-JP.txt
Various new translations, as well as an implementation for #1269.
> ja-JP: more translations; apply #1269.

- data/language/de-DE.txt
> de-DE: Apply #1257, #1259, #1269 and some fixes

- data/language/nb-NO.txt
> nb-NO: Apply #1269

- data/language/ar-EG.txt
- #1257
- #1259
- #1269 
also can i be a Maintainer for arabic??
> Update with missing strings (arabic)

- data/language/cs-CZ.txt
> cs-CZ: Apply #1285

- data/language/sv-SE.txt
> sv-SE: #1285

- data/language/it-IT.txt
> it-IT apply #1285

- data/language/ko-KR.txt
> ko-KR: Apply #1291 and enhance the translation

- data/language/sv-SE.txt
> sv-SE: Apply #1291

- data/language/cs-CZ.txt
> cs-CZ: Apply #1291

- data/language/it-IT.txt
> it-IT apply #1291

- data/language/ar-EG.txt
> ar-Eg Apply #1291 , #1285

- data/language/ko-KR.txt
* Fix date formatting
* Enhance scenario descriptions
> ko-KR: Fix date formatting + Enhance translations

- data/language/fr-FR.txt
- #1245
- #1257 
- #1259 
- #1269 
- #1285 
- #1291
> fr-FR: Apply #1245 #1257 #1259 #1269 #1285 #1291

- data/language/ko-KR.txt
> ko-KR: Apply #1300

- data/language/cs-CZ.txt
> cs-CZ: Apply #1300

- data/language/sv-SE.txt
> sv-SE: Apply 1300

- langcheck/LanguageParser.cs
> Make language checker recognise STR_VEHN

- data/language/ko-KR.txt
> ko-KR: Apply #1307

- data/language/cs-CZ.txt
> cs-CZ: Apply #1307

- data/language/it-IT.txt
> it-IT apply #1300, #1307

- data/language/sv-SE.txt
> sv-SE: Apply #1307

- data/language/zh-CN.txt
- #1245 
- #1257 
- #1259 
- #1269 
- #1285 
- #1291 
- #1300 
- #1307
> zh-CN: Apply #1245 #1257 #1259 #1269 #1285 #1291 #1300 #1307

- data/language/zh-TW.txt
#1245, #1257, #1259, #1269, #1285, #1291, #1307
> zh-TW: #1245, #1257, #1259, #1269, #1285, #1291, #1307

- data/language/cs-CZ.txt
> cs-CZ: Apply #1314

- data/language/ar-EG.txt
> Update ar-EG.txt With #1300 #1314 #1307

- data/language/it-IT.txt
> it-IT apply #1314

- data/language/es-ES.txt
#1245 #1257 #1259 #1269 #1285 #1291 #1300 #1307 
I'll translate the remaining strings (#1314) at the night, or tomorrow :P
Thanks!
> es-ES: Apply #1245 #1257 #1259 #1269 #1285 #1291 #1300 #1307

- data/language/ca-ES.txt
- #1245
- #1257
- #1259
- #1269
- #1285
- #1291
- #1300
- #1307
- #1314
> ca-ES: Apply #1245 #1257 #1259 #1269 #1285 #1291 #1300 #1307 #1314

- data/language/cs-CZ.txt
> cs-CZ: Apply #1321

- data/language/sv-SE.txt
> sv-SE: Apply #1321, #1314

- data/language/ko-KR.txt
> ko-KR: Apply #1321

- data/language/cs-CZ.txt
> cs-CZ: Apply #1325

- data/language/cs-CZ.txt
> cs-CZ: Apply #1326

- data/language/cs-CZ.txt
Also translated the works of a Czech author (Julius Fučík) (STR_2864)
> cs-CZ: Apply #1327

- data/language/ja-JP.txt
Addresses changes from #1291, #1300, #1307, #1314, #1325, #1326, #1327
> ja-JP: address #1291, #1300, #1307, #1314, #1325, #1326, #1327

- data/language/ko-KR.txt
> ko-KR: Apply #1325, #1326, #1327

- data/language/ar-EG.txt
- #1321 
- #1325 
- #1326 
- #1327
> ِArabic update with missing issues

- data/language/ja-JP.txt
More translations for Japanese, including for the new 6165 and 6166 strings.
> ja-JP: more translations; unify banner terminology

- data/language/cs-CZ.txt
> cs-CZ: Apply #1334

- data/language/cs-CZ.txt
> cs-CZ: Apply #1338

- data/language/it-IT.txt
- #1321 
- #1325 
- #1326 
- #1327 
- #1334 
- #1338
> it-IT: removed unused strings, new translations

- data/language/sv-SE.txt
- #1334
- #1338
- #1327
- #1326
- #1325
> sv-SE: Apply #1334, #1338, #1327, #1326, #1325

- data/language/ja-JP.txt
> ja-JP: apply #1344; various other strings

- data/language/ko-KR.txt
> ko-KR: Apply #1344

- data/language/cs-CZ.txt
> cs-CZ: Apply #1344

- data/language/de-DE.txt
- #1285
Will do the rest soon ;)
> de-DE: Apply #1285

- data/language/ko-KR.txt
> ko-KR: Apply #1349

- data/language/cs-CZ.txt
> cs-CZ: Apply #1349

- data/language/sv-SE.txt
> sv-SE: Apply #1334, #1344, #1349

- .github/ISSUE_TEMPLATE.md
- data/language/ar-EG.txt
- #1334 
- #1338 
- #1344 
- #1349
> Arabic Update with Missing Strings plus Add my self to Notification list

- data/language/it-IT.txt
> it-IT apply #1344 and #1349

- data/language/cs-CZ.txt
> cs-CZ: Apply #1356

- data/language/cs-CZ.txt
> cs-CZ: Apply #1359

- data/language/ko-KR.txt
> ko-KR: Applyh #1359

- data/language/ko-KR.txt
> ko-KR: Apply #1363

- data/language/cs-CZ.txt
>  cs-CZ: Apply #1363

- data/language/ar-EG.txt
> Update ar-EG.txt With missing strings and new words

- data/language/cs-CZ.txt
> cs-CZ: Apply #1367

- data/language/zh-TW.txt
> zh-TW apply #1326

- data/language/ca-ES.txt
> ca-ES apply #1326

- data/language/zh-CN.txt
> zh-CN apply #1326

- data/language/nb-NO.txt
> nb-NO apply 1326

- data/language/es-ES.txt
> es-ES apply #1326

- data/language/de-DE.txt
> de-DE apply 1326

- data/language/fr-FR.txt
> fr-FR: Apply #1326

- data/language/it-IT.txt
- #1356
- #1359
- #1363
- #1367
> it-IT apply #1356, #1359, #1363, #1367

- data/language/zh-TW.txt
- #1325
As the maintainer wont be able to update for a while
> zh-TW: Apply #1325

- data/language/nb-NO.txt
- #1325
As more issues are open that NO havent applied
> nb-NO apply #1325

- data/language/ko-KR.txt
> ko-KR: Apply #1367 and fix translations

- data/language/zh-CN.txt
- #1325 
Cus eh, less issues open :p
> zh-CN apply #1325

- data/language/es-ES.txt
- #1325 
Cus eh, less issues open :p 
(Last two strings already made)
> es-ES apply #1325

- data/language/ca-ES.txt
- #1325 
Cus eh, less issues open :p
> ca-ES apply #1325

- data/language/fr-FR.txt
- #1325 
Cus eh, less issues open :p
> fr-FR apply #1325

- data/language/de-DE.txt
- #1325 
Cus eh, less issues open :p
> de-DE apply #1325

- data/language/cs-CZ.txt
> cs-CZ: Apply #1386

- data/language/ko-KR.txt
> ko-KR: Apply #1386

- data/language/ja-JP.txt
> ja-JP: apply #1356, #1359, #1386; various other strings

- data/language/cs-CZ.txt
> cs-CZ: Apply #1390

- data/language/sv-SE.txt
> sv-SE apply #1363, #1367, #1386

- data/language/it-IT.txt
> it-IT: apply #1386, #1390

- data/language/sv-SE.txt
> sv-SE apply #1356 #1359 #1390

- data/language/cs-CZ.txt
> cs-CZ: Apply #1399 #1400

- data/language/de-DE.txt
- #1291 
- #1300 
- #1307 
- #1314 
- #1321 
- #1327 
- #1334 
- #1338 
- #1344 
- #1349 
- #1356 
- #1359 
- #1363 
- #1367 
- #1386 
- #1390 
- #1399 
- #1400
> de-DE: Some new translations

- .github/ISSUE_TEMPLATE.md
> Add myself to notification list

- data/language/pt-BR.txt
> pt-BR: Improved translation and typos

- data/language/cs-CZ.txt
> cs-CZ: slight improvements

- data/language/nl-NL.txt
Mostly corrections for vanilla translations (which are awful), plus some typo corrections and consistency fixes.
Doing a PR in case I messed up formatting.
> nl-NL: Fix many translations

- data/language/ko-KR.txt
> ko-KR: Apply #1411 and the Panda world

- data/language/zh-TW.txt
> zh-TW: catch up

- data/language/pt-BR.txt
> Update pt-BR.txt - Fixed some words

- data/language/sv-SE.txt
> sv-SE: Apply #1399

- data/language/cs-CZ.txt
> cs-CZ: Apply #1419

- data/language/it-IT.txt
> it-IT apply #1399, #1400, #1419

- data/language/it-IT.txt
> it-IT: apply #1424

- data/language/cs-CZ.txt
When initially translating the rides and objects I took care to translate as close in meaning as possible. Some strings (in my opinion) adhere well to the original meaning and can't be translated better. I went through all changed strings and, if possible, updated the translation.
> cs-CZ: Apply #1411

- data/language/cs-CZ.txt
> cs-CZ: Apply #1424

- data/language/sv-SE.txt
> sv-SE: Apply #1419, #1432

- data/language/cs-CZ.txt
> cs-CZ: Apply #1432

- data/language/ko-KR.txt
* Change a scenario name since it was a mistranslation
* Change a scenario description since it was too long
Sorry I don't know how to revert a commit yet. I'll learn ;)
I excepted about 'there is height restriction', just changing the name/desc. We'll talk about it later.
> ko-KR: Change a translation of 'Inca Lost City'

- data/language/cs-CZ.txt
> cs-CZ: Apply  #1442

- data/language/ar-EG.txt
- #1367 
- #1386 
- #1390 
- #1399 
- #1400 
- #1411
> Update ar-EG.txt With Missing strings ((o_o))

- data/language/fr-FR.txt
I added some french translations.
- #1338
- #1344
- #1349
- #1356
- #1359
- #1363
- #1367
- #1386
- #1390
- #1399
- #1419
- #1424
- #1432 
- #1442 
- #1300
- #1307
> Add some french translations

- data/language/de-DE.txt
- #1419 
- #1424 
- #1432 
- #1442 
- #1446
> de-DE: Apply #1419, #1424, #1432, #1442 and #1446

- data/language/it-IT.txt
> it-IT apply #1442, #1446

- data/language/cs-CZ.txt
cs-CZ: Apply #1446, #1451, #1450
> cs-CZ: Apply #1446, #1451, #1450

- data/language/cs-CZ.txt
> cs-CZ: Apply #1455 #1454

- data/language/sv-SE.txt
> Sv-SE: Apply #1455

- data/language/cs-CZ.txt
> cs-CZ: Apply #1461

- data/language/ko-KR.txt
> ko-KR: Apply #1461

- data/language/cs-CZ.txt
> cs-CZ: Apply #1465

- data/language/it-IT.txt
- #1450
- #1451
- #1454
- #1455
- #1461
- #1465
> it-IT: apply issues

- data/language/sv-SE.txt
> sv-SE: Apply 6936

- data/language/ko-KR.txt
> ko-KR: Apply #1473

- data/language/nl-NL.txt
> nl-NL: Apply #1478

- data/language/cs-CZ.txt
> cs-CZ: Apply #1481 #1478

- data/language/ar-EG.txt
- #1481 
- #1478 
- #1446 
- #1450 
- #1451 
- #1454 
- #1455 
- #1461 
- #1465 
- #1473
> Update ar-EG.txt with Missing Translation 

- data/language/it-IT.txt
> it-IT: apply #1473, #1478, #1481

- data/language/ko-KR.txt
> ko-KR: Apply #1487

- data/language/ko-KR.txt
Removes color tags per https://github.com/OpenRCT2/OpenRCT2/pull/7558
- #1487
> ko-KR: Apply #1487 (edit)

- data/language/nl-NL.txt
> nl-NL: Apply #1487

- data/language/cs-CZ.txt
> cs-CZ: Apply #1491

- data/language/nb-NO.txt
- #1285
- #1291
I'll try to slowly catch up now. Sorry for the absence :)
> nb-NO: Apply #1285 #1291

- data/language/ko-KR.txt
> ko-KR: Apply #1491

- data/language/nb-NO.txt
- #1300 
- #1307 
- #1314 
- #1321 
- #1327 
- #1334 
- #1338 
- #1344 
- #1349 
- #1356
And a small fix for an error I made in applying #1291
> nb-NO: Apply #1300 #1307 #1314 #1321 #1327 #1334 #1338 #1344 #1349 #1356 +fix

- data/language/cs-CZ.txt
> cs-CZ: Apply  #1487 #1496

- data/language/ko-KR.txt
> ko-KR: Apply #1496

- data/language/nl-NL.txt
> nl-NL: Apply #1496

- data/language/zh-TW.txt
#1399, #1432, #1419, #1424, #1442, #1446, #1451, #1455, #1454, #1461, #1450, #1465, #1473, #1478, #1491, #1481
If there are whitespace error again, please don't merge and I'll fix it asap.
_Untranslated strings for my references only:
#1487, #1496, #1501_
> zh-TW: catch up, part 1

- data/language/fr-FR.txt
- #1321
- #1327
- #1334
- #1400
- #1446
- #1450
- #1451
- #1454
- #1455
- #1465
- #1487
- #1496
- #1501
- #1473
- #1478
- #1481
> fr-FR: Apply #1321 #1327 #1334 #1400 #1446 #1450 #1451 #1454 #1455 #1465 #1487 #1496 #1501 #1473 #1478 #1481

- data/language/it-IT.txt
> it-IT apply #1487, #1496, #1501

- data/language/cs-CZ.txt
> cs-CZ Apply #1509 #1510

- data/language/de-DE.txt
Apply #1450, #1451, #1454, #1455, #1461, #1465, #1473, #1478, #1481, #1487, #1496, #1501, #1509 and #1510
> de-DE: Add and update strings

- data/language/ca-ES.txt
- #1321
- #1327
- #1338
- #1344
- #1349
- #1356
- #1359
- #1363
- #1367
- #1386
- #1390
- #1399
- #1400
- #1419
- #1424
- #1432
- #1442
- #1446
- #1450
- #1451
- #1454
- #1455
- #1461
- #1465
- #1473
- #1478
- #1481
- #1487
- #1496
- #1501
- #1509
- #1510
> Update ca-ES: Add strings from issues 1321-1510 and fix some spelling mistakes.

- data/language/es-ES.txt
The only thing I didn't do is the new JSON issue at 1470
- #1321 
- #1327 
- #1334 
- #1338 
- #1344 
- #1349 
- #1356 
- #1359 
- #1363 
- #1367 
- #1386 
- #1390 
- #1399 
- #1400 
- #1419 
- #1424 
- #1432 
- #1442 
- #1446 
- #1450 
- #1451 
- #1454 
- #1455 
- #1461 
- #1465 
- #1473 
- #1478 
- #1481 
- #1487 
- #1496 
- #1501 
- #1509 
- #1510
> Added and updated all strings up to issue #1510

- data/language/ca-ES.txt
> Add Catalan translation for RCT2 scenarios.

- data/language/es-ES.txt
No issues related, I fixed many problems in the es-ES.txt file, such as typos and mistakes, also things that didn't make sense because the meaning was lost during translation.
Also a change on Readme.md so now new translators know about the commit guideline.
> [es-ES] Fixes of the es-ES.txt file.

- data/language/es-ES.txt
No issues related, just missing translations.
In the future I'll start editing Wacky Worlds and Time Twister park descriptions.
> es-ES: Park Scenarios from RCT2 translated

- data/language/de-DE.txt
> de-DE: Use German quotation style

- data/language/fr-FR.txt
- #1509 
- #1510 
**WARNING:** Please ignore the first line change when merging, I don't know why it happens and that wasn't intentional at all.
> fr-FR: Apply #1509 #1510

- data/language/it-IT.txt
> it-IT apply #1509 #1510

- data/language/sv-SE.txt
#1400, #1424, #1442, #1446, #1450, #1451, #1454, #1461, #1465, #1478, #1487, #1481, #1496, #1501, #1509, #1510 #1446 #1451
> sv-SE apply new strings

- data/language/cs-CZ.txt
> cs-CZ: Apply #1542

- data/language/sv-SE.txt
> sv-SE apply 

- data/language/nb-NO.txt
- #1455
- #1461
- #1465
- #1478
- #1481
- #1487
- #1496
- #1501
- #1509
- #1510
- #1542
All caught up :)
> nb-NO: Apply #1455 #1461 #1465 #1478 #1481 #1487 #1496 #1501 #1509 #1510 #1542

- data/language/ja-JP.txt
- #1450
- #1454
- #1455
- #1461
- #1465
- #1478
- #1487
- #1501
- #1509
- #1510
- #1542
- #1545
> ja-JP: Translate more strings, catch up on new additions

- data/language/sv-SE.txt
> sv-SE: apply 

- data/language/fr-FR.txt
> fr-FR: Apply #1542 & #1545

- data/language/it-IT.txt
> it-IT apply #1542, #1545

- data/language/pl-PL.txt
> pl-PL work in progress

- data/language/cs-CZ.txt
> cs-CZ: Apply #1563

- data/language/es-ES.txt
> es-ES: Added String 6266

- data/language/ko-KR.txt
Change "Funnel cake" from "휜넬 케이크" into "퍼넬 케이크".
Related to OpenRCT2/objects/pull/31
- #1563
> ko-KR: Apply #1563 and change "Funnel cake"

- data/language/es-ES.txt
Reverts OpenRCT2/Localisation#1558
> Revert "es-ES: Added String 6266"

- data/language/es-ES.txt
Also several fixed typos and general cleanup.
Increased the word lenght to make it clearer in the shortcuts menu.
- #1563
> es-ES: Apply #1563

- .github/ISSUE_TEMPLATE.md
> Added a new mantainer to the notification list

- data/language/nb-NO.txt
- #1557
- #1563
Finished translations for Added Attractions and Loopy Landscapes.
> nb-NO: Apply #1557 & #1563 + Park descriptions

- data/language/sv-SE.txt
> sv-SE apply #1563

- data/language/it-IT.txt
Previous translations were not clear.
> it-IT - fixed "Wild Mouse" translations

- data/language/nb-NO.txt
> nb-NO: Fix missing space

- data/language/en-US.txt
In America I've never heard the phrase Is Good Value and rather always Is a Good Value.  This is related to OpenRCT2/OpenRCT2#8074 and OpenRCT2/OpenRCT2#8076.
> Grammatical Change To US English

- data/language/ca-ES.txt
- #1542
- #1545 
- #1557
- #1563
And some guillemets.
> Fix and add Catalan localisation

- data/language/ko-KR.txt
> ko-KR: Apply #1584

- data/language/cs-CZ.txt
> cs-CZ: Apply #1584

- data/language/hu-HU.txt
Many newly translated strings
+
* #1584
> Update hu-HU.txt, Apply #1584

- data/language/it-IT.txt
> it-IT apply #1584

- data/language/de-DE.txt
> Update string 6264, 6265, 2707

- data/language/es-ES.txt
I've noticed that some translations have an extra curly bracket at the end.
> es-ES: Fix some translations

- data/language/cs-CZ.txt
> cs-CZ update

- data/language/ko-KR.txt
> ko-KR: Apply #1604 and etc.

- data/language/cs-CZ.txt
> cs-CZ: Apply #1610

- data/language/hu-HU.txt
> hu-HU: Apply #1596 and #1604

- data/language/nl-NL.txt
- #1612
- #1610
- #1604
- #1596
> nl-NL: Apply #1612, #1610, #1604, #1596

- data/language/cs-CZ.txt
> cs-cz apply  #1612

- data/language/es-ES.txt
Done.
- #1604 
- #1610 
- #1612
> ES-es: Apply for #1604, #1610, #1612

- data/language/de-DE.txt
- #1557
- #1563
- #1596
- #1610
- #1612
> de-DE: Apply #1557, #1563, #1596, #1610, #1612

- data/language/cs-CZ.txt
> cs-cz apply #1620

- data/language/zh-CN.txt
- #1542 
- #1545 
- #1557 
- #1563 
- #1584 
- #1596 
- #1600 
- #1604 
- #1610 
- #1612 
- #1620 
- #1625
> zh-CN: Apply #1542, #1545, #1557, #1563, #1584, #1596, #1600, #1604, #1610, #1612, #1620, #1625

- .github/ISSUE_TEMPLATE.md
- data/language/fr-FR.txt
- #1557 
- #1563 
- #1584 
- #1596 
- #1600 
- #1604 
- #1610 
- #1612 
- #1620 
- #1625 
**Note:** I added myself in the issue template in order to get notified of future issues.
> [fr-FR] Apply #1557 #1563 #1584 #1596 #1600 #1604 #1610 #1612 #1620 #1625

- data/language/cs-CZ.txt
> cs-cz apply #1630

- data/language/fr-FR.txt
> fr-FR: Apply #1630

- data/language/it-IT.txt
> it-IT removed strings as in #1625

- data/language/sv-SE.txt
> sv-SE: Apply #1600

- data/language/it-IT.txt
#1596, #1604, #1610, #1612, #1620, #1630
> Apply it-IT issues #1596, #1604, #1610, #1612, #1620, #1630

- data/language/da-DK.txt
#1630
#1620
#1612
#1610
#1604
#1600
#1596
#1584
#1563
#1557
#1545
#1542
#1510
#1509
#1501
#1496
#1487
#1478 
#1424
> da-DK: Apply #1630 #1620 #1612 #1610 #1604 #1600 #1596 #1584 #1563 #1557 #1545 #1542 #1510 #1509 #1501 #1496 #1487 #1478  #1424 

- data/language/da-DK.txt
> apply da-DK: #1642

- data/language/cs-CZ.txt
> cs-cz apply #1642

- data/language/fr-FR.txt
> fr-FR: Apply #1642

- data/language/it-IT.txt
> it-IT apply #1642

- data/language/ar-EG.txt
Sorry For Late Update, But I have a very hard life with my college and my job (12 h a day)
I will try to keep Arabic updated as much as I can.
thanks
- #1648 
- #1642 
- #1612 
- #1620 
- #1625 
- #1630 
- #1584 
- #1600 
- #1596 
- #1604 
- #1610
> Update somewhat (O-O)|O_o

- data/language/ko-KR.txt
> ko-KR: Apply #1648

- data/language/fr-FR.txt
> fr-FR: Apply #1648

- data/language/da-DK.txt
> Update da-DK #1648

- data/language/nb-NO.txt
- #1584
- #1596
- #1600
- #1604
- #1610
- #1612
- #1620
- #1625
- #1630
- #1642
- #1648
> nb-NO: Apply #1596 #1600 #1584 #1604 #1610 #1612 #1620 #1625 #1630 #1642 #1648

- data/language/cs-CZ.txt
> cs-cz: apply #1648

- data/language/hu-HU.txt
- #1610 
- #1612
- #1620
- #1625
- #1630
- #1642
- #1648
> hu-HU: Apply #1610 #1612 #1620 #1625 #1630 #1642 #1648

- data/language/cs-CZ.txt
cs-cz: apply  #1659 #1656 #1657
> cs-cz: apply  #1659 #1656 #1657

- data/language/da-DK.txt
> Apply da-DK

- data/language/fr-FR.txt
> fr-FR: Apply #1656 #1657 #1659

- data/language/es-ES.txt
- #1625
- #1630
- #1642 
- #1648 
- #1656 
- #1657 
- #1659
> es-ES: Apply #1625 #1630 #1642 #1648 #1656 #1657 #1659

- data/language/hu-HU.txt
> hu-HU: Apply #1656 #1657 #1659

- data/language/en-US.txt
Changed litter to trash and changed litter bins to trash cans in en-US.txt.
> Use trash in en-US.txt

- data/language/ko-KR.txt
I shorten them since it was clipped because it was too long.
> ko-KR: Enhance translations

- data/language/ko-KR.txt
> ko-KR: Apply #1670

- data/language/ko-KR.txt
Fix some spacing words, spellings and typos. (띄어쓰기 밎 맞춤법 교정)
> ko-KR: Fix typos + a

- data/language/fr-FR.txt
> fr-FR: Apply #1670

- data/language/ko-KR.txt
> ko-KR: Apply #1675

- data/language/cs-CZ.txt
> cs-cz apply #1679

- data/language/fr-FR.txt
> fr-FR: Apply #1675 and #1679

- data/language/zh-CN.txt
- #1630 
- #1642 
- #1648 
- #1656 
- #1657 
- #1659 
- #1670 
- #1675 
- #1679
> zh-CN apply #1630 #1642 #1648 #1656 #1657 #1659 #1670 #1675 #1679

- data/language/zh-CN.txt
zh-CN apply All untranslated parts
> zh-CN apply All untranslated parts

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1670 #1675 #1679

- data/language/hu-HU.txt
> hu-HU: Updates and fixes

- data/language/de-DE.txt
- #1584
- #1604 
- #1630
- #1642
- #1648
- #1656
- #1657
- #1659
- #1670
- #1675
- #1679
> de-DE: Apply multiple issues

- data/language/sv-SE.txt
> sv-SE: Apply #1691

- data/language/cs-CZ.txt
> cs-cz apply #1691

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1691

- data/language/ko-KR.txt
> ko-KR: Apply #1698

- data/language/sv-SE.txt
> sv-SE: Apply #1698

- data/language/cs-CZ.txt
> cs-cz apply  #1698

- data/language/de-DE.txt
> de-DE: Apply #1691, #1697 & #1698

- data/language/cs-CZ.txt
> cs-cz apply  #1704

- data/language/fr-FR.txt
- #1691 
- #1697 
- #1698 
- #1704
> fr-FR: Apply #1691 #1697 #1698 #1704

- data/language/de-DE.txt
> de-DE: Apply #1704

- data/language/en-US.txt
> en-US: Apply #1691, #1697

- data/language/en-US.txt
Removed strings in en-US that were the same in en-GB
> Remove unnecessary strings in en-US.txt

- data/language/cs-CZ.txt
> cs-cz apply #1713

- data/language/cs-CZ.txt
> cs-cz apply #1718

- data/language/hu-HU.txt
- #1698 
- #1704 
- #1713 
- #1718 
- #1721
>  hu-HU: Update + Apply #1698 #1704 #1713 #1718 #1721

- data/language/ko-KR.txt
> ko-KR: Apply #1721

- data/language/cs-CZ.txt
> cs-cz apply #1721

- data/language/cs-CZ.txt
> cs-cz apply #1725

- data/language/hu-HU.txt
>  hu-HU: Update + Apply #1725

- data/language/fr-FR.txt
- #1713
- #1718
- #1721
- #1725
> fr-FR: Apply #1713 #1718 #1721 #1725

- data/language/ca-ES.txt
- #1725
- #1721
- #1718
- #1713
- #1704
- #1698
- #1697
- #1691
- #1679
- #1675
- #1670
- #1659
- #1657
- #1656
- #1648
- #1642
- #1630
- #1625
- #1620
- #1612
- #1610
- #1604
- #1600
- #1596
> ca-ES: Apply translations for issues from #1725 to #1596

- data/language/ko-KR.txt
Change EOL from LF into CRLF as the same as en-GB
> ko-KR: Modify some strings in multiplayer config

- data/language/ko-KR.txt
- #1737
And changed translations.
> ko-KR: Apply #1737

- data/language/cs-CZ.txt
> cs-cz apply  #1737

- data/language/pt-BR.txt
Applying PT-BR changes too all open issues that hadn't been applied yet:
- #1670   
- #1675 
- #1679 
- #1691 
- #1697 
- #1698 
- #1704 
- #1713 
- #1718 
- #1721 
- #1725 
- #1737
> Apply PT-BR translations

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1737

- data/language/nb-NO.txt
- #1679
- #1691
- #1697
- #1698
- #1704
- #1713
- #1718
- #1721
- #1725
- #1737
> nb-NO: Apply #1657 #1659 #1670 #1675 #1679 #1691 #1697 #1698 #1704 #1713 #1718 #1721 #1725 #1737

- data/language/es-ES.txt
- #1670
- #1679
- #1691
- #1697
- #1698
- #1704
- #1713
- #1718
- #1721
- #1725
- #1737
- #1745
> es-ES: Apply #1670, #1679, #1691, #1697, #1698, #1704, #1713, #1718, #1721, #1725, #1737, #1745

- data/language/pt-BR.txt
> Rewrite some PT-BR strings to avoid truncation

- data/language/it-IT.txt
- #1745 
- #1737 
- #1725
- #1721 
- #1718 
- #1713 
- #1704 
- #1698 
- #1697
- #1691
> it-IT: Updates

- data/language/fr-FR.txt
> fr-FR: Apply #1737 #1745

- data/language/ko-KR.txt
> ko-KR: Apply #1755

- data/language/cs-CZ.txt
> cs-cz apply #1755

- data/language/pt-BR.txt
> pt-BR: Apply #1755

- data/language/fr-FR.txt
> fr-FR: Apply #1755

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1755

- data/language/de-DE.txt
- #1755
- #1745
- #1737
- #1725
- #1721
- #1718
- #1713
- #1625
WARNING! Not tested! (but it was proofread)
> de-DE: Apply #1755, #1745, #1737, #1725, #1721, #1718, #1713, #1625

- data/language/de-DE.txt
Fixes a couple of incorrect or low quality translations in German.
Fixes <https://github.com/OpenRCT2/OpenRCT2/issues/10143>.
> de-DE: Various minor fixes

- data/language/de-DE.txt
> Update German strings, fixes #1773

- data/language/cs-CZ.txt
> cs-cz apply #1773

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1773

- data/language/ko-KR.txt
- #1781 
And changed & updated translations for hotkeys.
> ko-KR: Apply #1781 and etc.

- data/language/cs-CZ.txt
> cs-cz apply  #1781

- data/language/de-DE.txt
> [de-DE] Translate strings 6333-6348

- data/language/de-DE.txt
> de_DE: Translate string 6349

- data/language/hu-HU.txt
- #1781
- #1786
- #1789
- #1795
> hu-HU: Apply #1781, #1786, #1789, #1795

- data/language/fr-FR.txt
- #1773
- #1781 
- #1786 
- #1789 
- #1795
> fr-FR: Apply #1773 #1781 #1786 #1789 #1795

- data/language/fr-FR.txt
> fr-FR: Fix #1802

- data/language/de-DE.txt
> de_DE: Translate strings 6350-6355

- data/language/pt-BR.txt
- #1781
- #1786
- #1789
- #1795
- #1804
> Update ptbr translations

- data/language/ko-KR.txt
- #1809 
and modified <Karts & Coasters> scenario's description.
> ko-KR: Apply #1809 + etc

- data/language/pt-BR.txt
> Update PT-BR Translation

- data/language/de-DE.txt
> de-DE: Apply #1809

- data/language/ko-KR.txt
> ko-KR: Apply #1813

- data/language/pt-BR.txt
> pt-BR: Apply #1813

- data/language/de-DE.txt
> de-DE: Apply #1813

- data/language/fr-FR.txt
> fr-FR: Apply #1804 #1809 #1813

- data/language/ko-KR.txt
> ko-KR: Apply #1821 and missing 6360

- data/language/pt-BR.txt
> pt-BR: Apply #1821

- data/language/hu-HU.txt
- #1804
- #1809
- #1813
- #1821
> hu-HU: Apply #1804 #1809 #1813 #1821

- data/language/pt-BR.txt
> pt-BR: Apply #1826

- data/language/pt-BR.txt
> pt-BR: Apply #1828

- data/language/ko-KR.txt
> ko-KR: Apply #1826, #1828

- data/language/de-DE.txt
> de-DE: Apply #1821, #1826, #1828

- data/language/fr-FR.txt
> fr-FR: Apply #1821 #1826

- data/language/ja-JP.txt
- #1424
- #1451
- #1496
- #1584
- #1604
- #1630
- #1642
- #1648
- #1656
- #1697
- #1698
- #1704
- #1718
- #1721
- #1725
- #1737
- #1745
- #1755
- #1781
- #1786
- #1789
- #1795
- #1804
- #1809
- #1813
- #1821
- #1826
> ja-JP: catching up with recent strings

- .github/ISSUE_TEMPLATE.md
- README.md
- Sorts the languages on readme
- Sorts the usernames on the template to match the language order on readme.
- Adds everyone that is listed as a maintainer on the issue template
Before watching the repo, I thought all it took to be notified was being added as a maintainer in the README. Maybe some people are counting on it, so I'm syncing both sides.
- If you have been notified lately, and will continue to maintain a language, you don't need to do anything.
- If you haven't been notified in a while, but still want maintain a language, you might want to check the issues on your corresponding language to make sure it's up to date. We should have been notifying you but failed, sorry.
- If you haven't been notified in a while, and don't want maintain a language anymore, let us know so we take …
> Fix new issue notification

- data/language/pt-BR.txt
> pt-BR: Apply #1844 and #1847

- data/language/ko-KR.txt
- #1844
I've checked OpenRCT2/OpenRCT2/pull/11310 so merge this after it is merged
> ko-KR: Apply #1844, #1847 and fix a typo

- data/language/hu-HU.txt
> hu-HU: Update + Apply #1826 #1844 #1847

- data/language/ar-EG.txt
- data/language/ca-ES.txt
- data/language/cs-CZ.txt
- data/language/da-DK.txt
- data/language/de-DE.txt
- data/language/es-ES.txt
- data/language/fi-FI.txt
- data/language/fr-FR.txt
- data/language/hu-HU.txt
- data/language/it-IT.txt
- data/language/ja-JP.txt
- data/language/ko-KR.txt
- data/language/nb-NO.txt
- data/language/nl-NL.txt
- data/language/pl-PL.txt
- data/language/pt-BR.txt
- data/language/ru-RU.txt
- data/language/sv-SE.txt
- data/language/tr-TR.txt
- data/language/zh-CN.txt
- data/language/zh-TW.txt
Ties in with https://github.com/OpenRCT2/OpenRCT2/pull/11231
> Adjust STR_2781 for other languages

- data/language/pt-BR.txt
> pt-BR: Apply #1850

- data/language/de-DE.txt
> de-DE: STR6364-STR6367

- data/language/fr-FR.txt
> fr-FR: Apply #1844 #1847 #1850

- data/language/pt-BR.txt
> pt-BR: Apply #1858

- data/language/ko-KR.txt
> ko-KR: Apply #1862

- data/language/pt-BR.txt
> pt-BR: Apply #1862

- data/language/it-IT.txt
> it-IT apply #1862

- data/language/pt-BR.txt
> pt-BR: Apply #1866

- data/language/ko-KR.txt
> ko-KR: Apply #1866

- data/language/de-DE.txt
> de-DE: Apply #1858, #1862, #1866

- data/language/it-IT.txt
> it-IT: apply #1866, minor fixes
